Video in Heroic template
guardian/frontend pull request #14319
Opened 2016-09-15 11:38 UTC by blongden73

This allows to use the main video field in composer and displays the video correctly. 

**Before**
![picture 61](https://cloud.githubusercontent.com/assets/11950919/18548481/dab4f3ce-7b40-11e6-8121-c294ea964731.png)

**After**
![picture 60](https://cloud.githubusercontent.com/assets/11950919/18548486/e1cb7ea8-7b40-11e6-9172-81f154de0371.png)

@NataliaLKB @SiAdcock @desbo - would be great to get your input on this, currently I dont think this will work for AMP. 

Other thing to note, this is supposed to be going out Monday... :-s

2016-09-15 13:52 UTC, SiAdcock commented on common/app/views/fragments/immersiveVideo.scala.html
> +@(page: ContentPage)(implicit request: RequestHeader)
Maybe this file could be called `heroicVideo.scala.html` for consistency with the class names?

2016-09-15 13:55 UTC, SiAdcock commented
Looks good dude. As discussed, when you reinstate them inline styles I'll be happy with these changes.

I don't think any Heroic stuff was designed to work on AMP. Maybe in the future!

2016-09-15 14:35 UTC, desbo commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +      var player = $('.vjs-tech')[0];
might be worth wrapping this in a try/catch or checking that each of these elements exists

2016-09-15 14:58 UTC, gtrufitt commented on article/app/views/fragments/articleBodyHeroic.scala.html
> +            @if(article.content.tags.isLabourLiverpoolSeries){content--labour-liverpool}
The renderClasses helper may be useful:

```
class="@RenderClasses(Map(
                    "content content--article" -> true,
                    "content--labour-liverpool" -> article.content.tags.isLabourLiverpoolSeries,
                    "heroic--video" -> article.content.elements.hasMainVideo
                ))"
```

2016-09-15 15:21 UTC, desbo commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +        if($('.vjs-tech') && $('.labour-liverpool-headline') && $('.vjs-control-bar')){
just to avoid doing `$` twice you can move to after the `var`s and do `if (player && headline && controls)`

2016-09-15 15:24 UTC, gtrufitt commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +                bonzo(headline[0]).addClass('playing');
I think headline should be a bonzo object already so you should be able to do `headline.addClass` - same below

2016-09-15 15:25 UTC, gtrufitt commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +        if($('.heroic--video')){
You need to check for `$('.heroic--video').length > 0` here as `$` always returns an array (even if it's empty) so will always be true.

2016-09-15 15:25 UTC, gtrufitt commented on static/src/stylesheets/inline/article-labour-liverpool.scss
> +    padding-top: 12px;
Can this use the `$gs-baseline` var in some way?

2016-09-15 15:25 UTC, gtrufitt requested changes

2016-09-15 15:27 UTC, gtrufitt commented on static/src/stylesheets/inline/article-labour-liverpool.scss
> +            height: 128%;
Can you add a comment here just so we know what's going on when we come back to it?

2016-09-15 15:28 UTC, gtrufitt commented
👍 Once those couple of things are sorted. Sorry for using the changes requested thing, I wanted to see what it did

2016-09-15 15:43 UTC, desbo commented
ha, I've avoided using that so far because it seemed too aggressive

2016-09-15 15:45 UTC, gtrufitt commented
Ben can take it 😆

2016-09-15 15:53 UTC, blongden73 commented
I can take it.

2016-09-15 16:04 UTC, SiAdcock commented on static/src/stylesheets/inline/article-labour-liverpool.scss
> +            min-height: 27rem;
Would it be possible to convert these values to `px` rather than `rem`, just for consistency?

2016-09-16 09:21 UTC, gtrufitt approved these changes

2016-09-16 09:37 UTC, merged