Commercial containers - IE fix
guardian/frontend pull request #14380
Opened 2016-09-19 16:50 UTC by Calanthe

## What does this change?
Continuation of the https://github.com/guardian/frontend/pull/14207. Markup changes in `itemLargeCard.scala.html` and `itemSmallCard.scala.html`. Also fixes for the IE 11. There is still an issue with the wrong markup of badges. This will be done later.

## Screenshots
Before IE11:
![image_ 21](https://cloud.githubusercontent.com/assets/489567/18640539/92ce729e-7e90-11e6-8a7c-09f49d929537.png)

After IE11:
![screen shot 2016-09-19 at 15 52 00](https://cloud.githubusercontent.com/assets/489567/18640560/9f97cca0-7e90-11e6-919d-ee1d0c77d10e.png)

On IE9 it doesn't look perfect but every element is visible:
![screen shot 2016-09-19 at 17 20 42](https://cloud.githubusercontent.com/assets/489567/18640602/bc6fc076-7e90-11e6-8351-7491db614581.png)

![screen shot 2016-09-19 at 17 20 57](https://cloud.githubusercontent.com/assets/489567/18640613/c24033aa-7e90-11e6-9caf-6f24ce8711b9.png)

There is a lot of js errors in IE9 and I keep getting new ones every time I open the inspect tool:
![screen shot 2016-09-19 at 17 20 24](https://cloud.githubusercontent.com/assets/489567/18640652/eeb2102a-7e90-11e6-8db4-d702456a804f.png)

Imo it's not worth polishing IE9 any more.

## Request for comment
@regiskuckaertz

2016-09-20 08:50 UTC, regiskuckaertz commented on common/app/views/commercial/cards/itemLargeCard.scala.html
> +        <div class="advert__image-container @for(imgRatio <- optImgRatio){u-responsive-ratio u-responsive-ratio--@imgRatio}">
The image is not clickable then?

2016-09-20 08:54 UTC, regiskuckaertz commented on common/app/views/commercial/cards/itemCard.scala.html
> +       class="advert__container">
I thought `.advert__container` would be used for the surrounding `DIV` 😅  The idea is that everything that happens inside an `.advert` (its layout and sizes and stuff) does not need to apply to the surrounding `DIV`.

2016-09-20 08:59 UTC, regiskuckaertz commented on common/app/views/commercial/cards/itemCard.scala.html
> +       class="advert__container">
In fact, I think the whole IE11 bug is caused by a selector in [_adverts.scss line 204](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/module/commercial/_adverts.scss#L204) that I wrote 😭  Instead, it should be: `.advert__row .advert__image-container`, not `.advert__row > * > .advert__image-container`

2016-09-20 09:07 UTC, regiskuckaertz requested changes
I think these changes demonstrate some pitfalls in the CSS I originally wrote (sorry 😞 ), in particular that I used wrong combinations of direct child selectors where, like the .advert__image-container example above. I'll pull your branch and try to fix that.

2016-09-20 14:38 UTC, Calanthe commented on common/app/views/commercial/cards/itemLargeCard.scala.html
> +        <div class="advert__image-container @for(imgRatio <- optImgRatio){u-responsive-ratio u-responsive-ratio--@imgRatio}">
Yes! It should be clickable.

2016-09-20 14:39 UTC, Calanthe commented
@regiskuckaertz Are you going to continue working on this issue?

2016-09-20 16:25 UTC, regiskuckaertz commented
@Calanthe yes! I may be able to fix this quicker.

2016-10-13 14:03 UTC, regiskuckaertz commented
Reviving this PR @Calanthe 

Before:
![picture 3](https://cloud.githubusercontent.com/assets/629976/19352031/2a9ab434-9156-11e6-8601-81190e7520bf.jpg)

After:
![picture 4](https://cloud.githubusercontent.com/assets/629976/19352034/2db9583c-9156-11e6-862f-96e827bc5c23.jpg)

2016-10-13 14:04 UTC, regiskuckaertz commented
(logos are not showing up because some weird vibe with browserstack)

2016-10-13 14:08 UTC, regiskuckaertz commented
@lps88 mind reviewing this one I took from Zofia?

2016-10-14 14:12 UTC, regiskuckaertz approved these changes

2016-10-14 14:13 UTC, lps88 commented
👍  LGTM

2016-10-14 14:13 UTC, regiskuckaertz commented
Nice nice nice! Thanks @lps88

2016-10-14 14:14 UTC, merged