Jobs JSON endpoint
guardian/frontend pull request #14455
Opened 2016-09-26 14:57 UTC by regiskuckaertz

Same old same old.

![picture 1](https://cloud.githubusercontent.com/assets/629976/18839147/dc459e04-8401-11e6-82ae-6e9627a32937.jpg)

2016-09-26 16:25 UTC, JonNorman commented on commercial/app/controllers/commercial/JobsController.scala
> +        JsonComponent(json)
You can now use the thuper thexy [`JsonComponent(jobSample(specificIds, segment))`](https://github.com/guardian/frontend/blob/master/common/app/common/JsonComponent.scala#L17) (merged this morning). It now has a generic constructor so, as long as it has an implicit `Writes` object, you can pass any old thing in.

This saves you converting it to Json yourself, I know, so much effort.

2016-09-26 16:27 UTC, JonNorman requested changes
Looks good to me! Apart from the note about the `JsonComponent`, go right ahead.

2016-09-26 17:15 UTC, TBonnin commented on commercial/app/model/commercial/jobs/Job.scala
> +  )(unlift(Job.toJsonTuple))
You can also create a `new Writes[Job]` and define inside the `writes(job: Job): JsValue` method like done [here](https://github.com/guardian/frontend/blob/b2527874ac8f94f4d61b1bed2d91f0d930b5c590/admin-jobs/app/models/BreakingNews.scala#L30-L42) so you don't have to define this weird intermediary tuple data structure

2016-09-26 17:19 UTC, TBonnin commented on commercial/app/controllers/commercial/JobsController.scala
>        case Nil => NoCache(jsonFormat.nilResult.result)
I know you have not modified it but why are we not caching the empty result (even for a very short period of time)?
Not caching it at all means that if we return no jobs, all requests made to this endpoint will hit our origin as long as we keep returning an empty results.

2016-09-27 09:37 UTC, regiskuckaertz commented on commercial/app/model/commercial/jobs/Job.scala
> +  )(unlift(Job.toJsonTuple))
@TBonnin Thanks! Much cleaner, me likey

2016-09-27 09:38 UTC, regiskuckaertz commented on commercial/app/controllers/commercial/JobsController.scala
>        case Nil => NoCache(jsonFormat.nilResult.result)
Doing that, good call.

2016-09-27 10:45 UTC, regiskuckaertz commented
@TBonnin @JonNorman happy with my changes?

2016-09-27 10:47 UTC, JonNorman commented
I'm happy with them, but I've made similar changes in my PR https://github.com/guardian/frontend/pull/14466 - might be good to get a second opinion to sense check them ( @TBonnin 😄  )

2016-09-27 10:47 UTC, JonNorman approved these changes

2016-09-27 10:48 UTC, merged

2016-09-27 10:50 UTC, TBonnin reviewed
lgtm 👍

2016-09-27 10:50 UTC, TBonnin commented on commercial/app/controllers/commercial/JobsController.scala
> +      }
Don't change it but you can write this in one line. ie: `case Nil => Cached(60)(jsonFormat.nilResult)`