Remove redundant DFP logo handling code
guardian/frontend pull request #14492
Opened 2016-09-28 11:55 UTC by kelvin-chappell

This gets rid of a lot of redundant code, and some redundant work done by the admin server.
With luck it should have no effect on the site.

/cc @guardian/commercial-dev

2016-09-28 12:40 UTC, JonNorman commented on admin/app/dfp/DfpDataCacheJob.scala
> +      loadLineItems()
Perhaps not for this PR, but is that list exhaustive of the DFP sources we would want to refresh?

2016-09-28 12:45 UTC, kelvin-chappell commented on admin/app/dfp/DfpDataCacheJob.scala
> +      loadLineItems()
I think there are more reading jobs since this code was written, so probably not.

2016-09-28 12:58 UTC, regiskuckaertz commented
![picture 3](https://cloud.githubusercontent.com/assets/629976/18914120/a27c3ad8-8583-11e6-927c-743422de4dd6.jpg)

😍

2016-09-28 13:09 UTC, regiskuckaertz commented on facia/app/views/fragments/frontBody.scala.html
> +                data-sponsor="@branding.sponsorName"
Why aren't these two data attributes removed entirely?

2016-09-28 13:10 UTC, JonNorman commented on common/app/layout/Front.scala
>        case MostPopular => ContainerCommercialOptions.mostPopular(omitMPU)
Do we still need `mostPopular` and `empty` given that they each just wrap `ContainerCommercialOptions`?

2016-09-28 16:08 UTC, JonNorman commented on common/app/model/meta.scala
> -    ("isAdvertisementFeature", JsBoolean(isAdvertisementFeature))
I assume that there isn't anything that continues to rely on this flag client-side?

2016-09-28 16:15 UTC, JonNorman approved these changes
A few minor questions from me and Regis but otherwise this beautiful wrenching out of DFP logos has a :+1: from me.

2016-09-28 16:22 UTC, TBonnin requested changes

2016-09-28 16:22 UTC, TBonnin commented on admin/test/dfp/DfpDataCacheJobTest.scala
>    with WithTestContentApiClient {
you can remove 
```
   with BeforeAndAfterAll
   with WithTestWsClient		    
   with WithTestContentApiClient {
```
if you are not using the testContentApiClient anymor

2016-09-29 10:55 UTC, kelvin-chappell commented on common/app/layout/Front.scala
>        case MostPopular => ContainerCommercialOptions.mostPopular(omitMPU)
No.  They seem pretty redundant so I'll get rid of them.

2016-09-29 10:56 UTC, kelvin-chappell commented on common/app/model/meta.scala
> -    ("isAdvertisementFeature", JsBoolean(isAdvertisementFeature))
We'll soon find out! I'll do a search through the js code.

2016-09-29 10:57 UTC, kelvin-chappell commented on admin/test/dfp/DfpDataCacheJobTest.scala
>    with WithTestContentApiClient {
Thanks.  Will do.

2016-09-29 15:44 UTC, kelvin-chappell commented on common/app/model/meta.scala
> -    ("isAdvertisementFeature", JsBoolean(isAdvertisementFeature))
It's already set [here](https://github.com/guardian/frontend/blob/master/common/app/model/PressedPage.scala#L37) and [here](https://github.com/guardian/frontend/blob/kc-dfp-logo-go/common/app/model/content.scala#L229) so should be safe.

2016-09-29 16:11 UTC, TBonnin approved these changes

2016-10-03 08:44 UTC, merged