Hosted Article - 'more from' carousel
guardian/frontend pull request #14649
Opened 2016-10-11 16:35 UTC by lps88

## What does this change?
Add new functionality to the 'More from' component, so the user can scroll through more of the campaign's other pages. Currently switched off until both new variants are finished.

## What is the value of this and can you measure success?
There will be an AB test to measure whether this works better (i.e. gets more people to click through) than the current design.

## Screenshots
![image](https://cloud.githubusercontent.com/assets/6290008/19279310/d5247554-8fd8-11e6-8ac6-bbd611aa1f9c.png)

## Request for comment
@guardian/labs-beta

2016-10-12 10:39 UTC, kelvin-chappell requested changes
Looks good but some of the code is redundant or not obviously related.

2016-10-12 10:39 UTC, kelvin-chappell commented on commercial/conf/routes
> +GET         /advertiser-content/:campaignName/:pageName/:cType/onward.json  commercial.controllers.HostedContentController.renderOnwardComponent(campaignName, pageName, cType, items: Option[Int])
Could get rid of new `items` param.

2016-10-12 10:39 UTC, kelvin-chappell commented on static/src/javascripts/projects/common/modules/experiments/tests/hosted-more-from.js
> +            return /*config.isHosted && */config.page.contentType === 'Gallery';
Can this commented out condition be removed?

2016-10-12 10:39 UTC, kelvin-chappell commented on static/src/javascripts/projects/commercial/modules/hosted/onward.js
> +            var query = contentType === 'article' ? '?items=12' : '';
This becomes redundant if number of items is set in controller.

2016-10-12 10:39 UTC, kelvin-chappell commented on commercial/app/controllers/HostedContentController.scala
> +              val trails = HostedTrails.fromContent(itemId, trailCount = items.getOrElse(2), results)
Could change this to `trailCount = <large number>` and then get rid of new `items` param.

2016-10-12 10:39 UTC, kelvin-chappell commented on static/src/javascripts/projects/common/modules/experiments/tests/hosted-more-from.js
> +});
This file should probably be put in a separate PR.

2016-10-12 10:39 UTC, kelvin-chappell commented on static/src/javascripts/projects/common/modules/experiments/ab.js
>      var participationsKey = 'gu.ab.participations';
This file should probably be in a separate PR.

2016-10-12 10:39 UTC, kelvin-chappell commented on common/app/conf/switches/ABTestSwitches.scala
> +  )
This switch should probably be in a separate PR.

2016-10-12 10:39 UTC, kelvin-chappell commented on commercial/app/controllers/HostedContentController.scala
> +              val trails = HostedTrails.fromContent(itemId, trailCount = items.getOrElse(2), results)
And then building hosted trails becomes a lot simpler so could be done in a different def, without specifying a trail count at all.  But that could be done in a separate PR.

2016-10-13 14:41 UTC, kelvin-chappell approved these changes

2016-10-13 14:41 UTC, kelvin-chappell commented on dev-build/conf/routes
> +GET            /$path<commercial-containers>                                                                                                controllers.FaciaController.renderFront(path)
Looks the same to me.

2016-10-13 16:03 UTC, lps88 commented on dev-build/conf/routes
> +GET            /$path<commercial-containers>                                                                                                controllers.FaciaController.renderFront(path)
I think I accidentally committed some whitespace changes...!

2016-10-14 13:34 UTC, merged