Fix Media Atom rendering race condition
guardian/frontend pull request #14644
Opened 2016-10-11 14:55 UTC by gidsg

## What does this change?
The previous YouTube cleaner added in #14618 was intermittently failing due to a race condition whereby it relied on `AtomsCleaner` to have run prior to `YouTubeAtomCleaner` in order to find the DOM elements it depended on.

This PR fixes the issue by moving the rendering of Media atoms into a template called by `AtomsCleaner`. 

## What is the value of this and can you measure success?
YouTube templating is more reliable. Template logic is better encapsulated.

## Does this affect other platforms - Amp, Apps, etc?
No

## Screenshots
N/A

## Request for comment
@akash1810 @markjamesbutler @TBonnin

2016-10-11 16:07 UTC, akash1810 commented on common/app/views/fragments/atoms/media.scala.html
> +            <iframe id="youtube-@media.assets.head.id" width="420" height="315"
can we width and height with css?

2016-10-11 16:41 UTC, akash1810 approved these changes

2016-10-11 16:56 UTC, TBonnin requested changes

2016-10-11 16:56 UTC, TBonnin commented on common/app/views/fragments/atoms/media.scala.html
> +@defining(media.assets.head.platform == "Youtube") { isYouTube =>
Can we differentiate YoutubeAtom and MediaAtom and extract this logic out of this template? For instance something like this in `atom.scala.html`
```
model match {
    case quiz: Quiz => views.html.fragments.atoms.quiz(quiz, maybeResults = None, false, Nil)
    case media: YoutubeAtom => views.html.fragments.atoms.youtube(media, origin)
    case media: MediaAtom => views.html.fragments.atoms.media(media)
    case _ =>		        
```

2016-10-13 09:20 UTC, TBonnin approved these changes

2016-10-13 11:35 UTC, merged