Only add a badge to the first facia container that ISN'T a thrasher.
guardian/frontend pull request #14752
Opened 2016-10-21 17:20 UTC by JonNorman

#### Background / Problem
If a front is sponsored/branded, then we add a badge to the first container on that page. However, in the cases where there is a thrasher, we want to add the badge to the one below it i.e. we want to add the badge to the first _non-thrasher_ container on a sponsored front.

#### Solution
We can have multiple thrashers on a given front and so only the front fragment being rendered can determine which container should hold the badge, and it must do this by inspecting the container objects it is about to render. This requires each `FaciaContainer` knowing whether or not it is a thrasher.

#### Disclaimer
I'm not proud of this - it seems a bit gross inspecting the layout name to determine whether a `FaciaContainer` is a thrasher or not but, short of creating a new field in FAPI that explicitly specifies which container should have a branded badge on, I think this is the best/easiest solution.

@kelvin-chappell

2016-10-22 13:43 UTC, JonNorman commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Sponsored by" badge appearing in thrasher on podcasts page.](https://trello.com/c/cf3rLSY4/102-sponsored-by-badge-appearing-in-thrasher-on-podcasts-page)

2016-10-24 08:29 UTC, kelvin-chappell requested changes
Looks like the best solution.  Just a small suggestion to clarify the template.

2016-10-24 08:29 UTC, kelvin-chappell commented on applications/app/views/fragments/indexBody.scala.html
> +                                        showFrontBranding =  containerDefinition.index == containerIndexForBadge)
Could the evaluation of `containerIndexForBadge` be done in a support def elsewhere?
`Defining` blocks in templates are best avoided unless the value is used multiple times.
So something like `def shouldShowFrontBranding(index, containers): Boolean`.

2016-10-24 10:06 UTC, kelvin-chappell approved these changes

2016-10-24 10:40 UTC, merged

2016-10-24 10:42 UTC, JonNorman commented
Yep, I reckon they probably can - doesn't seem to be anything obviously different about them at first glance...