initial stab at testing documentation for frontend
guardian/frontend pull request #14809
Opened 2016-10-27 17:52 UTC by michaelwmcnamara

Adds some testing documentation to the frontend docs.

2016-10-28 08:59 UTC, scottp719 requested changes
Nice so far! Left come comments but think there's lots of good stuff here. Once we have this in I will add some notes I've put together for commercial testing.

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +
Before getting on to running sbt it might be worth mentioning running make install/make compile for the JavaScript?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +- To test on a variety of devices or to reproduce a bug on a particular set up, use https://www.browserstack.com. This site has a collection of computers and devices,
Maybe instead -> 
`This tool contains both real and simulated versions of a most popular devices, browsers and operating systems. `
Not sure computers is the right terminology, OS would be more specific?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +[A list of what browsers we support](https://github.com/guardian/frontend/blob/master/docs/04-quality/01-browser-support.md);
`which browsers`

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> + Add to this the fact that it is much older than IE11 so supports even less features. IE9 is the oldest browser version that we expect to be fully supported. If it works on IE9 it is a good indicatio
I don't think that's true anymore, last time we discussed I believe we agreed that IE11 was now the lowest we fully support. See https://frontend.gutools.co.uk/analytics/quality - all the older versions have now left our top browsers (even when cut my time of day).

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +- Chrome and Firefox on windows 10 - IE10 is slowly overtaking Windows7 as our users most popular desktop OS. When Windows 10 originally came out, firefox had some rendering issues and Chrome and fir
Windows 10?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +- Chrome and Firefox on windows 10 - IE10 is slowly overtaking Windows7 as our users most popular desktop OS. When Windows 10 originally came out, firefox had some rendering issues and Chrome and fir
rendering

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +- Older devices - A common source of problems comes from older devices. Where the device is running the latest operating system, it will attempt to run all the latest features and give the fullest ex
catastrophic

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +  This is especially important if your feature is very resource heavy. For reasons unknown, but possibly connected to the way safari manages memory, iOS devices have proved more susceptable
Worth mentioning the special rules we have for iPad fronts due to this fact, would be useful to call out?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +- Devices with strange screen sizes. If you re interested in layout and rendering for your change, the iphone 5S is a popular device with an abnormally narrow screen,
you're

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +- Test on AMP! [Google are making amp the default in mobile search results](http://searchengineland.com/amp-live-in-google-259109).
I wonder whether amp should get it's own section lower down, I think there's other stuff after it but amp (and I will do one for ad testing as well) should be sub-sections?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> + This combination often throws up interesting layout problems. In addition Safari often has less support for new features compared with Chome, which can also lead to rendering errors.
Chrome

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +### How to find examples of pages you want to test
Should this section be further up the page and then amp as a separate section? See note above but think that would be clearer?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +### Testing Amp pages on the live website
Are there exceptions where we don't use amp (fronts perhaps?), maybe mention here?

2016-10-28 08:59 UTC, ScottPainterGNM commented on docs/01-start-here/06-testing-tips.md
> +### Testing Amp pages on the live website
I could be wrong though, its been a while.

2016-10-28 10:54 UTC, jbreckmckye commented on docs/01-start-here/06-testing-tips.md
> +- Older devices - A common source of problems comes from older devices. Where the device is running the latest operating system, it will attempt to run all the latest features and give the fullest ex
Sudden crashes are a dead giveaway that the browser has exhausted memory.

2016-10-31 16:59 UTC, michaelwmcnamara commented on docs/01-start-here/06-testing-tips.md
> +
Great idea! - I've added a little bit to this effect.

2016-10-31 17:45 UTC, michaelwmcnamara commented on docs/01-start-here/06-testing-tips.md
> +### Testing Amp pages on the live website
A good point! Amp is only available for articles and liveblogs. I've updated docs to this effect.

2016-10-31 17:51 UTC, michaelwmcnamara commented on docs/01-start-here/06-testing-tips.md
> +[A list of what browsers we support](https://github.com/guardian/frontend/blob/master/docs/04-quality/01-browser-support.md);
This is linked out to existing documentation as I don't want to have to maintain this in multiple places.
See - https://github.com/guardian/frontend/blob/master/docs/04-quality/01-browser-support.md

2016-11-02 15:08 UTC, merged