Use scanamo for redirects, centralise
guardian/frontend pull request #14864
Opened 2016-11-02 19:40 UTC by jfsoul

## What does this change?
Consolidates logic for inserting, removing and reading from the `redirect` dynamo tables.  There is now a single service which uses Scanamo to interact with dynamo.  

There are still a number of other dynamo interactions in frontend that still use the AWS SDK directly - I haven't switched these yet as there isn't as strong a case for it (redirects made a bare request with `wsClient`).  For these other interactions, though, I have at least moved them to use a single `DynamoDB` service for initialising the client.

## What is the value of this and can you measure success?
This is largely an exercise in centralising logic:
- Redirect table(s) interactions happen in one place
- Dynamo client is initialised in one place (and only once)

Bonus: net reduction in LOC! 🔪 

## Does this affect other platforms - Amp, Apps, etc?
No

## Request for comment
N.B. the diff isn't particularly helpful: `DynamoDB.scala` was renamed to `Redirects.scala`.

@TBonnin 

cc: @philwills: wondering whether there might be a better way to interact with the `redirect` table via scanamo.  Particularly thinking about the `Redirects.Redirect` case class with `Option`s.

2016-11-02 19:44 UTC, jfsoul commented on admin/app/css_report/CssReport.scala
> -  dynamoDbClient.setRegion(Region.getRegion(Regions.EU_WEST_1))
We were doing this in a number of places - but the client is thread safe.

2016-11-02 19:44 UTC, jfsoul commented on admin/app/jobs/R2PagePressJob.scala
> -                  }
Removed warnings for redundant braces in a few places here

2016-11-02 19:46 UTC, jfsoul commented on common/app/services/DynamoDB.scala
> +    client
This might be overkill just for the 2 client types, but definitely DRY...

2016-11-03 09:32 UTC, jfsoul commented on archive/test/ArchiveControllerTest.scala
> +  }
Planning to create a `WithTestDynamoClient` trait or similar which will mean this mocking isn't required, but I'll do that in another PR.  This one is already too bloated.

2016-11-03 17:51 UTC, TBonnin requested changes

2016-11-04 11:02 UTC, jfsoul commented on common/app/services/Redirects.scala
> +object Redirects {
I think so yes, the only reason I didn't was consistency - we don't tend to use that naming convention (in `common` services anyway)

2016-11-04 11:18 UTC, jfsoul commented on admin/app/controllers/RedirectController.scala
> +      case PageRedirect(from, "") if from.nonEmpty  => redirects.remove(from)
I'll include this as part of next PR on the redirect tool UI

2016-11-04 11:22 UTC, jfsoul commented
Thanks for comments @TBonnin (naming is hard 😢 ).  Agree in all cases and have made changes.

@philwills thanks for the help - using `Destination` directly now - although there might be a neater way.

2016-11-04 12:03 UTC, TBonnin approved these changes

2016-11-04 14:22 UTC, merged

2016-11-04 15:24 UTC, philwills commented
@jfsoul That looks like a reasonable way of doing it to me. You could probably do something slightly marginally neater, but I don't think it would help with clarity much.