make section related calls iff section exists
guardian/frontend pull request #14901
Opened 2016-11-04 21:14 UTC by akash1810

## What does this change?
More in series and end-slate relies on page section. If the section doesn't exist then the requests 404. See console on https://www.theguardian.com/global/video/2016/nov/01/what-happened-at-the-battle-of-orgreave-video-explainer for example.

This change checks page section exists before making api calls.

## What is the value of this and can you measure success?
Fewer 404s

## Does this affect other platforms - Amp, Apps, etc?
No. Will very likely need to replicate on off platform embed player in a later PR.

## Screenshots
n/a

## Request for comment
@gidsg @markjamesbutler

2016-11-04 21:31 UTC, akash1810 commented on common/app/model/VideoPlayer.scala
> +  // TODO make Option[String] as relies on section being set
if there isn't a section `endSlatePath` will 404 - it shouldn't be on the DOM in this case

2016-11-05 11:57 UTC, paperboyo commented
I may be entirely wrong, but maybe it should just call for latest videos from the tag instead of ending up empty? Would be https://www.theguardian.com/politics/miners-strike-1984-85+type/video for the above example.

2016-11-07 09:41 UTC, akash1810 commented
@paperboyo it doesn't end up empty as the fallback behaviour is to show the most popular videos

2016-11-07 10:59 UTC, gidsg requested changes

2016-11-07 10:59 UTC, gidsg commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +        if (config.page.section) {
There are already logic checks inside `initMoreInSection()` function, so I think this extra check would make more sense to do there?

2016-11-07 11:46 UTC, akash1810 commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +        if (config.page.section) {
yeah I debated on putting it in there. My argument for putting it here was that the function name `initMoreInSection` sounds like it expects section to exist... it was a weak argument so happy to change.

2016-11-07 11:51 UTC, akash1810 commented on static/src/javascripts/bootstraps/enhanced/media/main.js
> +        if (config.page.section) {
updated.

2016-11-07 12:14 UTC, gidsg approved these changes

2016-11-07 12:26 UTC, merged