This birds gonna fly...er
guardian/frontend pull request #15142
Opened 2016-11-28 18:08 UTC by superfrank

## What does this change?
Email banner added for The Flyer test
## What is the value of this and can you measure success?
Naa
## Does this affect other platforms - Amp, Apps, etc?
Naa
## Screenshots
![the-flyer](https://cloud.githubusercontent.com/assets/6727874/20680120/a7e98bd2-b595-11e6-85e2-a01b1533e024.png)
## Request for comment
@joelochlann

2016-11-28 18:15 UTC, joelochlann requested changes

2016-11-28 18:15 UTC, joelochlann commented on common/app/model/EmailAddons.scala
> +  def test(c: ContentPage) = c.item.tags.series.exists(_.id == "travel/series/the-flyer")
no need for this `test` line, the test for front emails is the same for all of them and is on line 18 (it's different from article emails where each new email published is a new article with the same series tag - there's only one front per email and the front changes over time, so the test just checks if the page title matches the name of the email)

2016-11-28 18:17 UTC, joelochlann commented
Loving the GIF

2016-11-29 12:01 UTC, superfrank commented on common/app/model/EmailAddons.scala
> +  def test(c: ContentPage) = c.item.tags.series.exists(_.id == "travel/series/the-flyer")
got ya 👍  thanks.

2016-11-29 12:07 UTC, joelochlann approved these changes

2016-11-29 12:09 UTC, merged