autoplay youtube media atoms (under certain conditions)
guardian/frontend pull request #15534
Opened 2017-01-11 11:37 UTC by gidsg

## What does this change?

Autoplays youtube media atom if user:
* Is on a Video page
* Has an internal referrer 
* Not on Android or iOS *(as these OS's block autoplay)*

CC @guardian/accessibility we might want to turn this off if a user has disabled flashing elements?

## What is the value of this and can you measure success?

Required for YouTube PFP trial feature parity

## Does this affect other platforms - Amp, Apps, etc?
No

## Screenshots
![autoplay](https://cloud.githubusercontent.com/assets/1764158/21847141/29f28556-d7f2-11e6-9a3e-454e0f7ce492.gif)

2017-01-11 11:40 UTC, PRBuilds commented
PR build results: 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15534/screenshots/mobile.png 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15534/screenshots/wide.png 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15534/screenshots/tablet.png 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15534/screenshots/desktop.png 

 -automated message

2017-01-11 11:49 UTC, akash1810 commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            const isIOS = () => /(iPad|iPhone|iPod touch)/i.test(navigator.userAgent);
this is a `javascripts-legacy` module - do we want to be writing ES6 here @sndrs ?

2017-01-11 11:49 UTC, akash1810 commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            const isIOS = () => /(iPad|iPhone|iPod touch)/i.test(navigator.userAgent);
should we put this flag on the `config` object so others can benefit from it?

2017-01-11 11:49 UTC, akash1810 commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +        return config.page.contentType == 'Video' && isInternalReferrer() && !isMobile();
`===` because javascript 😄

2017-01-13 11:45 UTC, sndrs commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            const isIOS = () => /(iPad|iPhone|iPod touch)/i.test(navigator.userAgent);
this shouldn't be es6 no, i'm surprised it linted? it won't be transpiled anyway. 

you probably also want to use https://github.com/guardian/frontend/blob/master/static/src/javascripts-legacy/projects/common/utils/detect.js#L164

2017-01-13 11:48 UTC, sndrs requested changes
arrow functions will fail on around 30% of our visitors.

2017-01-13 11:50 UTC, sndrs requested changes

2017-01-13 11:50 UTC, sndrs commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +        function isMobile() {
you probably want https://github.com/guardian/frontend/blob/master/static/src/javascripts-legacy/projects/common/utils/detect.js#L164-L170

2017-01-13 11:50 UTC, sndrs commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +                return document.referrer.startsWith(window.location.origin);
`startsWith` does not have wide support

2017-01-13 13:16 UTC, sndrs requested changes

2017-01-13 13:16 UTC, sndrs commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            if (!String.prototype.startsWith) {
this isn't really a good idea, I'm afraid... 

firstly, how would anyone else have any idea that it's been polyfilled in this module? if they wanted to polyfill it to, we'd be doing twice (at least).

secondly, you're changing the prototype of `String` directly, meaning that at any point before this code is evaluated, the _global_ `String` does not contain the `startsWith` method, and then after, it does. This introduces side affects to the entire environment, just so this string can be checked.

it's generally much better practise to create a method that returns the native method if exists.

however, for something that really only needs to be done once, it's not clear it even really needs polyfilling, especially when you could use the polyfill you've added directly, or maybe

```js
if(config.page.isDev) {
    return document.referrer.indexOf(window.location.origin) === 0;
}
else {
    return document.referrer.indexOf(config.page.host) === 0;
}
```

2017-01-13 13:20 UTC, sndrs commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            return isIOS() || isAndroid();
is this really the check you want? isMobile doesn't really seem to equal being iOS or android does it? do you want a breakpoint maybe?

2017-01-13 13:22 UTC, sndrs commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            return detect.isIOS() || detect.isAndroid();
is this really the check you want? isMobile doesn't really seem to equal being iOS or android does it? do you want a breakpoint maybe?

2017-01-13 13:45 UTC, gidsg commented on static/src/javascripts-legacy/projects/common/modules/atoms/youtube.js
> +            return detect.isIOS() || detect.isAndroid();
Yes, this is specifically the check I want as these platforms block autoplay at the OS level.

2017-01-13 14:13 UTC, sndrs approved these changes

2017-01-13 14:33 UTC, merged