Turn off end slate for in-body YouTube atom embeds and don't show YT player on small cards
guardian/frontend pull request #15660
Opened 2017-01-23 14:07 UTC by gidsg

## What does this change?
This changes the *show endslate* and *show video* conditions to be closer to that applied to non-YouTube atoms.

However, the *show video* condition for YouTube atoms is set to false for smaller cards in order to meet the YouTube PFP minimum size requirements.

## What is the value of this and can you measure success?
Makes end-slate behaviour consistent with non-youtube videos.
Make small cards non-playable (Required to meet minimum player size requirement for YouTube PFP.)

## Does this affect other platforms - Amp, Apps, etc?
No

## Screenshots
Before:
![screen shot 2017-01-23 at 14 04 41](https://cloud.githubusercontent.com/assets/1764158/22206936/00cca990-e175-11e6-859c-fe543ec7c87f.png)

After:
![screen shot 2017-01-23 at 14 02 09](https://cloud.githubusercontent.com/assets/1764158/22206920/f54783ba-e174-11e6-8dfb-6e48ca991c6a.png)

## Tested in CODE?

2017-01-23 14:26 UTC, PRBuilds commented
PR build results:
screenshots > [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15660/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png 
) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15660/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png 
) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15660/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png 
) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15660/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png 
)
other > [thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15660/thrown-exceptions.js 
) • [performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15660/performanceComparisonSummary.txt 
)

 -automated message

2017-01-23 15:53 UTC, GHaberis commented on common/app/views/fragments/items/facia_cards/contentCard.scala.html
> +            case Some(media@InlineYouTubeMediaAtom(_)) if item.cardTypes.showYouTubeMediaAtomPlayer => {
So if showYouTubeMediaAtomPlayer is false we don't render the youtube template fragment at all? I wonder if we could still use this template but pass showYouTubeMediaAtomPlayer as an argument. We can then put the logic to check this argument in that template; if true we add the iframe and if false we add the play button and overlay (which link through to the video page). +'ve is It'd save us having a new template? -'ve is more logic in that template.

2017-01-23 15:59 UTC, gidsg commented on common/app/views/fragments/items/facia_cards/contentCard.scala.html
> +            case Some(media@InlineYouTubeMediaAtom(_)) if item.cardTypes.showYouTubeMediaAtomPlayer => {
Yes, that would be possible but we'd need to design that template, so I thought it better to do that in a subsequent PR.

2017-01-23 16:00 UTC, GHaberis commented on common/app/views/fragments/items/facia_cards/contentCard.scala.html
> +            case Some(media@InlineYouTubeMediaAtom(_)) if item.cardTypes.showYouTubeMediaAtomPlayer => {
Yeah that's fine, that's probably how I'd do it but we can make that change in the following PR.

2017-01-23 16:02 UTC, gidsg commented on common/app/views/fragments/items/facia_cards/contentCard.scala.html
> +            case Some(media@InlineYouTubeMediaAtom(_)) if item.cardTypes.showYouTubeMediaAtomPlayer => {
Let's see how much the template varies from the current playable one. It may be cleaner to make it its own fragment like `posterOnly` case.

2017-01-23 16:02 UTC, GHaberis reviewed
@gidsg this look good to me. It'd be good for someone more Scala orientated like @TBonnin from frontend to check on this too?

2017-01-24 16:25 UTC, TBonnin requested changes
I made 2 tiny comments but lgtm

2017-01-24 16:25 UTC, TBonnin commented on article/app/views/package.scala
> +        AtomsCleaner(article.content.atoms, shouldFence = true, amp, mainMedia = true)
Can we either have named parameters everywhere or no at all? You can put one param per line

2017-01-24 16:25 UTC, TBonnin commented on common/app/views/fragments/atoms/youtube.scala.html
> +    }
I think you can do something like this
```
@for {
   endSlate <- media.endSlatePath if(displayEndSlate)
}
```

2017-01-25 11:37 UTC, TBonnin approved these changes

2017-01-26 11:32 UTC, merged