make amp embed cleaner embed facebook videos from non guardian sources
guardian/frontend pull request #15868
Opened 2017-02-17 12:36 UTC by michaelwmcnamara

This is a change to the amp embed cleaner so that it will handle embedded facebook videos that are not from the guardian. For example [this page](https://amp.theguardian.com/global/commentisfree/2017/feb/16/first-dates-going-dutch-bill-splitting-channel-4#development=1) contains a facebook video embed from channel4.

This change fixes a [trello card](https://trello.com/c/pumy9Trr/228-non-guardian-amp-facebook-video-embeds-are-causing-validation-to-fail)

This change only effects amp pages
all tests pass 
validate-amp tests all pass

## Tested in CODE?
No.

2017-02-17 15:07 UTC, gidsg requested changes

2017-02-17 15:07 UTC, gidsg commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      //val facebookPattern = """^https?:\/\/www\.facebook\.com\/theguardian\/videos\/(\d+)\/""".r
remove commented out line.

2017-02-17 15:07 UTC, gidsg commented on common/test/views/support/cleaner/AmpEmbedCleanerTest.scala
>        "https://facbook.com.zz/theguardian/123456/",
I don't think you really have to so extensively test your regex! But I suppose it does not do any harm

2017-02-17 16:56 UTC, michaelwmcnamara commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      //val facebookPattern = """^https?:\/\/www\.facebook\.com\/theguardian\/videos\/(\d+)\/""".r
oops! Thanks, good spot!

2017-02-17 17:04 UTC, michaelwmcnamara commented on common/test/views/support/cleaner/AmpEmbedCleanerTest.scala
>        "https://facbook.com.zz/theguardian/123456/",
Thats actually a good point! I'll strip out the extra pages as they dont really add anything.

2017-02-20 08:52 UTC, SiAdcock commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/(\w+)\/videos\/(\d+)\/""".r
Is there any chance the organisation might contain non-alphabetic characters such as digits or a `-`?

2017-02-20 14:16 UTC, michaelwmcnamara commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/(\w+)\/videos\/(\d+)\/""".r
w+ matches digits and letters.
As far as I my powers of google can tell me - facebook usernames (which is where that bit comes from) only allow alphanumeric chars. You can include full stops, but they won't be recognized as part of the username so likely they are not included in the url either.
https://www.facebook.com/help/105399436216001

2017-02-20 14:18 UTC, michaelwmcnamara commented on common/test/views/support/cleaner/AmpEmbedCleanerTest.scala
>        "https://facbook.com.zz/theguardian/123456/",
@gidsg  These change requests should be resolved in the latest commit.
Cheers

Mike

2017-02-21 16:28 UTC, gidsg commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/(\w+)\/videos\/(\d+)\/""".r
@michaelmcnamara I think you need a wider regex to include hyphens. I think you could use `((\w|\W))` I tested this on http://rubular.com/

2017-02-21 16:32 UTC, gidsg commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/(\w+)\/videos\/(\d+)\/""".r
@michaelmcnamara you should allow for `.` in your regex e.g. https://www.facebook.com/gideon.goldberg

2017-02-21 17:31 UTC, michaelwmcnamara commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/(\w+)\/videos\/(\d+)\/""".r
@gidsg @SiAdcock  Just made a change to cater for usernames with '.' (good spot both of you!).
Let me know if this is ok and I'll merge it tomorrow morning.

2017-02-21 17:40 UTC, gidsg commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/(\w+)\/videos\/(\d+)\/""".r
@michaelmcnamara did you commit this, I don't see any new commit?

2017-02-22 11:27 UTC, gidsg commented on common/app/views/support/cleaner/AmpEmbedCleaner.scala
> +      val facebookPattern = """^https?:\/\/www\.facebook\.com\/([\w.-]+)\/videos\/(\d+)\/""".r
I don't think `-` is allowed but `.` is. This is according to the guidelines you linked to.

2017-02-22 11:31 UTC, michaelwmcnamara commented
@gidsg  Hi, this should now only allow chars, numbers or '.' chars.

2017-02-22 11:32 UTC, gidsg commented on common/test/views/support/cleaner/AmpEmbedCleanerTest.scala
> +    result.getElementsByTag("amp-facebook").attr("data-href") should be(s"https://www.facebook.com/$facebookOrganisationId/videos/$faceookVideoId")
I would not bother repeating all these other tests for this additional case. Just the first `result.getElementsByTag("amp-facebook").size should be(1)` I think is sufficient.

2017-02-22 11:34 UTC, PRBuilds commented
PR build results:

screenshots
[mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15868/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15868/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15868/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15868/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png)
    
exceptions (1)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15868/thrown-exceptions.js)    

webpagetest (0)
[performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15868/performanceComparisonSummary.txt)

-automated message

2017-02-22 11:38 UTC, michaelwmcnamara commented on common/test/views/support/cleaner/AmpEmbedCleanerTest.scala
> +    result.getElementsByTag("amp-facebook").attr("data-href") should be(s"https://www.facebook.com/$facebookOrganisationId/videos/$faceookVideoId")
good point.

2017-02-22 11:40 UTC, michaelwmcnamara commented
@gidsg  Hi mate, thats been tidied up now.

2017-02-22 11:47 UTC, gidsg approved these changes

2017-02-22 11:48 UTC, gidsg commented
Looks good to me once you rebase to get tests to pass. 👍

2017-02-22 12:14 UTC, merged

2017-02-22 12:15 UTC, michaelwmcnamara commented
@gidsg  Thanks for your help with this! Shipping now. :-)