Add test for Sleeve Notes emails
guardian/frontend pull request #15996
Opened 2017-03-01 14:35 UTC by lmath

## What does this change?
A/B test for the new Sleevenotes email

- Current subscribers will continue to receive the same version (listId=39).
- For new subscribers, the new version of Sleeve Notes is the default (listId=3834). 
- 30% of new subscribers will be in a control group subscribed to the old email (listId=3835).

Then we can compare old and new versions of the email across just new subscribers. 

## What is the value of this and can you measure success?
Allows us to test a new version of the Sleeve Notes email.

## Does this affect other platforms - Amp, Apps, etc?
No. 
## Screenshots

## Tested in CODE?
No.

2017-03-01 14:38 UTC, lmath commented
@davidfurey has done some work to make it simpler to create files like sleeve-notes-email-variants.js so I'm going to try and apply that here.

2017-03-01 14:39 UTC, PRBuilds commented
PR build results:

screenshots
[mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15996/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15996/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15996/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15996/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png)
    
exceptions (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15996/thrown-exceptions.js)    

webpagetest (0)
[performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15996/performanceComparisonSummary.txt)

-automated message

2017-03-01 15:29 UTC, joelochlann requested changes

2017-03-01 15:29 UTC, joelochlann commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/sleeve-notes-email-variants.js
> +                var input = $('input[value=${newSleevenotesListId.toString()}]')[0];
Does this actually work!? I think you need backticks for variable substitution in a string. And even with the backticks, it's an ES6 feature, so there's no support in IE. We'll be able to use this and other ES6 features once we're bundling all our modules with webpack but we're still not quite there yet (@SiAdcock can confirm this!)

2017-03-01 15:29 UTC, joelochlann commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/sleeve-notes-email-variants.js
> +        this.audience = 0.6;
I would start of with an audience size of 0. Then you can deploy live, opt into the test and manually test in production, then deploy a change setting the audience size to the correct amount

2017-03-01 15:36 UTC, davidfurey reviewed
Seems fine, but is it not possible to share some of the code sleeve-notes-email-variants.js across other email a/b tests?

2017-03-01 15:36 UTC, davidfurey commented on common/app/model/EmailNewsletters.scala
> +    listId = 3834,
It might make sense to switch the primary listId based on the AB test switch, so that the new list ID is only enabled when the test is enabled.

2017-03-01 15:55 UTC, lmath commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/sleeve-notes-email-variants.js
> +                var input = $('input[value=${newSleevenotesListId.toString()}]')[0];
Ok, noted. Thanks.

2017-03-06 11:16 UTC, davidfurey commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/email-variant-example.js
> +define([
I think you can delete this file

2017-03-06 11:25 UTC, lmath commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/email-variant-example.js
> +define([
Oh, right. Agreed. I will do that.

2017-03-06 12:48 UTC, joelochlann commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/generic-email-variants.js
> +        this.id = props['id'];
Using square bracket notation with string literals for accessing object properties is stylistically a bit weird (https://github.com/airbnb/javascript#properties) - best to stick with dot notation unless you're using a variable as the key

2017-03-06 12:55 UTC, joelochlann approved these changes

2017-03-06 14:11 UTC, merged