ab server side recipe test
guardian/frontend pull request #16136
Opened 2017-03-14 19:02 UTC by tsop14

## What does this change?
- Adds mvt for new recipe design
- Adds ability to opt in to test
- Sets `showNewRecipeDesign` to true if an article has recipe atoms (is eligible) and the feature is enabled.
- If `showNewRecipeDesign` and user is participating in test - shows the new recipe template.

While running the test, for articles which are eligible for new design but requested by users in the control group:
- Sets argument `recipePageNotInTest` on article template to true. This is used to set `displayNormalHeader` to ensure correct header (not slim) is displayed.
- Sets same js-features as normal article.

## What is the value of this and can you measure success?
Work towards running server-side ab test on new recipe design. 

## Does this affect other platforms - Amp, Apps, etc?
No.

## Screenshots

## Tested in CODE?
No

To see new design:

1. Enable feature switch
2. Enable ab server side test
3. Set `X-GU-ab-new-recipe-design` header to true

TODO
- [ ] test with fastly
- [ ] Add 50:50 buckets on fastly

Thanks @gidsg for the help!

2017-03-14 19:08 UTC, PRBuilds commented
PR build results:

screenshots
[mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16136/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16136/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16136/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16136/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png)
    
exceptions (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16136/thrown-exceptions.js)    

webpagetest (1)
[performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16136/performanceComparisonSummary.txt)

-automated message

2017-03-15 14:36 UTC, gidsg commented on common/app/model/content.scala
> +  lazy val showNewRecipeDesign: Boolean = ArticleWithStructuredRecipe.isSwitchedOn && hasRecipeAtom
Do you still need this switch, given that the AB test is also a switch? You could just check `ABNewRecipeDesign.switch.isSwitchedOn` for equivalence?

2017-03-15 15:20 UTC, tsop14 commented on common/app/model/content.scala
> +  lazy val showNewRecipeDesign: Boolean = ArticleWithStructuredRecipe.isSwitchedOn && hasRecipeAtom
I think you're right - will remove feature switch.

2017-03-16 10:04 UTC, tsop14 commented
@regiskuckaertz for the changes in `commercial-features.js`
@guardian/dotcom-platform

T🐝H🐝A🐝N🐝K🐝S

2017-03-16 10:27 UTC, gidsg commented on static/src/javascripts-legacy/bootstraps/enhanced/main.js
> +                });
I don't think you need these `=== true` I think just doing 
`if (config.page.showNewRecipeDesign)` is equivalent?

2017-03-16 10:41 UTC, regiskuckaertz commented on static/src/javascripts-legacy/bootstraps/enhanced/main.js
> +            if (config.tests.abNewRecipeDesign != undefined && config.tests.abNewRecipeDesign === true) {
Assuming that `abNewRecipeDesign` is either `true`, `false` or `undefined`, you can just write `if(config.tests.abNewRecipeDesign)`

2017-03-16 10:42 UTC, regiskuckaertz commented on static/src/javascripts-legacy/bootstraps/enhanced/main.js
> +                require(['bootstraps/enhanced/recipe-article'], function (recipes) {
@SiAdcock shouldn't this sit in a `require.ensure` call instead?

2017-03-16 10:42 UTC, tsop14 commented on static/src/javascripts-legacy/bootstraps/enhanced/main.js
> +                });
Great, wasn't sure if it was sometimes set to `false`. Will change.

2017-03-16 10:43 UTC, regiskuckaertz commented on static/src/javascripts-legacy/projects/commercial/modules/commercial-features.js
> +        var newRecipeDesign = config.page.showNewRecipeDesign && (config.tests.abNewRecipeDesign != undefined && config.tests.abNewRecipeDesign === true);
`var newRecipeDesign = config.page.showNewRecipeDesign && config.tests.abNewRecipeDesign;`

2017-03-16 10:44 UTC, regiskuckaertz commented on static/src/javascripts-legacy/projects/commercial/modules/commercial-features.js
> +            switches.commercial;
Please scrap the `switches.commercial` here.

2017-03-16 10:44 UTC, regiskuckaertz commented on static/src/javascripts-legacy/projects/commercial/modules/commercial-features.js
> +            switches.commercial;
ditto

2017-03-16 10:44 UTC, regiskuckaertz commented on static/src/javascripts-legacy/projects/commercial/modules/commercial-features.js
> +        this.sliceAdverts =
... you probably need to merge master, these lines should not be there.

2017-03-16 10:44 UTC, NataliaLKB commented on applications/app/controllers/OptInController.scala
> +      case "abnewrecipedesign" => ABNewRecipeDesignOverride.opt(choice)
Nit: this doesn't have the AB prefix and doesn't need it. I probably would remove it for consistency sake

2017-03-16 10:45 UTC, regiskuckaertz requested changes
Few JS stuff to get rid of.

2017-03-16 10:50 UTC, NataliaLKB commented on static/src/javascripts-legacy/bootstraps/enhanced/main.js
> +                });
Even if it is set to `false`, then the conditional will still be `false` so `if (config.page.showNewRecipeDesign)` is still accurate

2017-03-16 14:09 UTC, tsop14 commented on applications/app/controllers/OptInController.scala
> +      case "abnewrecipedesign" => ABNewRecipeDesignOverride.opt(choice)
Cool and I've updated in fastly PR too

2017-03-16 16:49 UTC, tsop14 commented
@regiskuckaertz changes made. 
@SiAdcock does this need to change? -> https://github.com/guardian/frontend/pull/16136#pullrequestreview-27303517

2017-03-16 16:56 UTC, regiskuckaertz approved these changes
YAY!

2017-03-17 09:54 UTC, merged