[WIP] Navigation: Add "more" toggle in sub navigation
guardian/frontend pull request #16478
Opened 2017-04-18 17:31 UTC by gustavpursche

## What does this change?

This adds another navigation entry in the sub navigation at the end of the list, which toggles the sidebar, but opens the current pillar. This saves one click compared to the veggi-burger.

It also updates the colors of the navigation and enhances accessibility. 🎨 

## What is the value of this and can you measure success?

We'll see, but hopefully more user engangement with the navigation.

## Does this affect other platforms - Amp, Apps, etc?

No.

## Screenshots

No.

## Tested in CODE?

Not yet.

2017-04-18 19:44 UTC, paperboyo commented
> Screenshots
> 
> No.

![screenshot](https://cloud.githubusercontent.com/assets/6032869/25149871/dcae78ea-2477-11e7-8e66-5170cbcd2337.jpg)

2017-04-19 10:20 UTC, TBonnin requested changes
Thank you @gustavpursche 
I made a couple of comments related to the Scala code. Let me know if you want to discuss them.

2017-04-19 10:20 UTC, TBonnin commented on common/app/common/NewNavigation.scala
> +      }.getOrElse("News")
It is only a matter of preference but I like to have one piece of logic per line. Something like:
```
sectionList
    .map(_.parentSection.name)
    .getOrElse("News")
```

You can even chain everything together:
```
sectionLinks
    .find(_.pageId == id)
    .map(_.parentSection.name)
    .getOrElse("News")
```

2017-04-19 10:20 UTC, TBonnin commented on common/app/common/NewNavigation.scala
> +    def getParentPillar(id: String) = {
It is good practice to specify the return type for every function. The compiler is smart enough to figure it out but it is easier for developer to understand what is this function doing by only looking at the full signature.

2017-04-19 10:20 UTC, TBonnin commented on common/app/common/NewNavigation.scala
> +    def getActivePillar(page: Page) = {
Can you add the return type?

2017-04-19 10:20 UTC, TBonnin commented on common/app/common/NewNavigation.scala
> +      }.getOrElse("")
Is this exactly the same logic as `getParentPillar` with a different default?

2017-04-19 10:20 UTC, TBonnin commented on common/app/common/NewNavigation.scala
> +      (sectionOrTagId, activePillarName)
Would it make sense to create a case class `Pillar` to carry these data, rather than using a tuple?

2017-04-19 12:06 UTC, TBonnin commented on common/app/common/NewNavigation.scala
> +    }
Are `getSectionLinks` and `getSectionLink` only supposed to use internally? If yes make them `private`

2017-04-19 12:06 UTC, TBonnin commented on common/app/views/fragments/nav/subNav.scala.html
> +                }">
nitpick: Keeping it on one line might make it easier to read the html source

2017-04-19 12:09 UTC, gustavpursche commented on common/app/common/NewNavigation.scala
> +    }
Good catch.

2017-04-19 12:13 UTC, gustavpursche commented on common/app/mvt/MultiVariateTesting.scala
> +  sellByDate = new LocalDate(2017, 4, 21)
You are right - talked with Stephan in the morning about it. We'll run it till Monday.

2017-04-19 12:18 UTC, TBonnin approved these changes

2017-04-19 14:23 UTC, NataliaLKB commented on static/src/stylesheets/_vars.scss
> +$subnav-grey: #5c6268;
Okay, now you have to add a screen shot! Or a gif of the more button working

2017-04-19 15:29 UTC, merged