Use a better solution to fix the ID test that doesnt work in local
guardian/frontend pull request #16536
Opened 2017-04-21 16:48 UTC by DiegoVazquezNanini

This PR fix an issue with some ID tests that fail if you run the tests locally.
@jfsoul @markjamesbutler @TBonnin

2017-04-21 17:22 UTC, TBonnin commented
Something like this https://gist.github.com/TBonnin/7b11368f841796dbcb286c5fe4e12cec in addition to your changes of `IdApi` and IdApiClient` should do the job.
Then in all the tests involving identity config you can define your own implementation of the `IdConfig` trait

2017-04-21 17:24 UTC, TBonnin requested changes
Something like this https://gist.github.com/TBonnin/7b11368f841796dbcb286c5fe4e12cec, in additions to your changes of `IdApi` and `IdApiClient`, would be cleaner.

Then in all the tests involving identity config you can provide your own implementation of the `IdConfig` trait, the same way we are providing `TestWsClient` for instance.

2017-04-24 15:43 UTC, DiegoVazquezNanini commented
@TBonnin please let me know what do you think now and please let me know if you have further suggestions.

2017-04-25 10:01 UTC, TBonnin commented on identity/test/package.scala
> +    val domain: String = ???
You are gonna need real values here

2017-04-25 10:02 UTC, DiegoVazquezNanini commented on identity/test/package.scala
> +    val domain: String = ???
Yeap, I'm working on a fix now.

2017-04-25 10:25 UTC, PRBuilds commented
PR build results:

screenshots
[mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16536/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16536/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16536/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16536/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png)
    
exceptions (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16536/thrown-exceptions.js)    

webpagetest (2)
[performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16536/performanceComparisonSummary.txt)

-automated message

2017-04-25 10:35 UTC, TBonnin approved these changes

2017-04-25 10:42 UTC, DiegoVazquezNanini commented
Thanks for the review @TBonnin

2017-04-25 10:44 UTC, merged