Give myself more relevant es6 conversions
guardian/frontend pull request #16571
Opened 2017-04-26 17:47 UTC by joelochlann

I'd like to start off by converting all the acquisitions-related JS so I've swapped with the relevant people.

I also added two files not in the list (probably added after it was created):
- `projects/common/modules/commercial/contributions-utilities.js`
- `projects/common/modules/experiments/tests/acquisitions-epic-liveblog.js`

cc @dominickendrick @jranks123 @Mullefa

2017-04-26 17:51 UTC, PRBuilds commented
PR build results:

screenshots
[mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16571/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16571/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16571/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16571/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png)
    
exceptions (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16571/thrown-exceptions.js)    

webpagetest (3)
[performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16571/performanceComparisonSummary.txt)

-automated message

2017-04-26 20:08 UTC, sndrs requested changes
should probably remove `tools/es5to6-files-per-user.js` too now, because if it's run again this will all change. can always resurrect it if we need it

2017-04-27 10:03 UTC, joelochlann commented
Thanks @sndrs, have removed

2017-04-27 10:39 UTC, sndrs approved these changes
go for it

2017-04-27 11:28 UTC, merged