Update facia architecture documentation
guardian/frontend pull request #16585
Opened 2017-04-27 16:13 UTC by TBonnin

## What does this change?
Updating and adding details to Fronts architecture docs.
Main new document is here: https://github.com/guardian/frontend/blob/8bfff0bf3077cbf3dfd0b85679588ecf4dcee1c9/docs/02-architecture/02-fronts-architecture.md
I have also moved the section related to monitoring and alerts into its own file.

Let me know if this is understandable. Don't hesitate to correct my english or fix typos. Thank you @guardian/dotcom-platform 

## What is the value of this and can you measure success?
Better docs 📜 🏅

2017-04-27 16:17 UTC, PRBuilds commented
PR build results:

screenshots
[mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16585/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16585/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16585/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16585/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png)
    
exceptions (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16585/thrown-exceptions.js)    

webpagetest (3)
[performanceComparisonSummary.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-16585/performanceComparisonSummary.txt)

-automated message

2017-04-27 16:46 UTC, jfsoul requested changes
This is really great, I especially love the glossary. 💯 

I am afraid I have just been a grammar nerd and suggested some corrections.

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +Rendering a front requires to fetch a lot of information from multiple sources (CAPI, Fronts config, Fronts collections). In order to avoid doing this grueling work inline when an user request is rec
requires ~~to fetch~~ fetching

~~grueling~~ gruelling

sorry 🤓

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +- [Facia press](#facia-press): for each front, fetch all necessary data, aggregate it and store it into S3
store it in~~to~~ s3

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +It is not an user facing service, it processes events published to queues.
not a~~n~~ user facing

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +- one queue where the Fronts tool (fronts.gutools.co.uk) publishes events to when a front is being updated.
events ~~to~~ when

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +1. Get the collections that compose the front by fetching the Fronts config at `s3://facia-tool-store/STAGE/frontsapi/config/config.json` in the CMS Fronts account. This file is edited using the Conf
link to the config tool here?

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +Reacting to a new event published to the queues described above Facia-press then:
Maybe reword this? How about:

> In reaction to a new event published to the queues described above, Facia-press will:

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +- A collection type correspond to its layout.
corresponds

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +Each collection would contain the `id` and `metadata` for all their running stories that have been curated by editors using the Fronts tool.
collection ~~would~~ will contain

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +As mentioned above when Facia receive a request for a front, it:
receives

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +Each row would contained cards.
Each row contains cards?

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +Here is the defition of a few words and expression related to fronts:
expressions

2017-04-27 16:46 UTC, jfsoul commented on docs/02-architecture/02-fronts-architecture.md
> +_Trasher_:
Thrasher! 😄

2017-04-27 17:01 UTC, jfsoul approved these changes
Made my corrections, only suggestion remaining was about the link to the config tool.  I will leave that up to you to decide on.

2017-04-27 17:12 UTC, TBonnin commented
Thanks @jfsoul

2017-04-27 17:40 UTC, NataliaLKB approved these changes
Thanks for doing this! Really helpful for the team

2017-04-28 11:25 UTC, stephanfowler commented on docs/02-architecture/02-fronts-architecture.md
> -The global list of defined fronts - and the definitions of the collections on those fronts - is held in a single configuration file (`config.json`). This file is edited using the Configuration Tool.
I think this paragraph is worth keeping. The key role of `config.json`, and knowing how it gets edited, seems important to state.

2017-04-28 11:36 UTC, kelvin-chappell approved these changes
Very clear and useful description.
Just a couple of comments (and some trivial nitpicking).

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +```
Might be useful to distinguish between behaviour of draft and live presses?  Eg. behaviour when front is not yet published and the pressing schedule.

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +1. Get the collections that compose the front by fetching the Fronts config at `s3://facia-tool-store/STAGE/frontsapi/config/config.json` in the CMS Fronts account. This file is edited using the Conf
Is the Configuration tool different to the Fronts tool?  Maybe a URL here?

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +Here is the definition of a few words and expressions related to fronts:
> are the definitions

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +A way to include arbitrary content into a collection (rather than a story).
> in a container

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +A type of container which contains a single full-width element.
> that

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +A way to further tweak the layout of a collection. Dynamic collections can have multiple groups (standard/snaps or huge/veryBig/big/standard). Depending on the group a story/content is in, the layout
> will be

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/facia/facia-monitoring.md
> +## Succesive press failures - MANUAL presser (facia-tool)
> Successive

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/facia/facia-monitoring.md
> +* __Detail__ : immediately after a collection is edited within the Fronts Editor, the Presser is invoked to re-create the `pressed.json` files for any front containing that collection.
> regenerate?

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/facia/facia-monitoring.md
> +* __Detail__ : every three minutes, the Admin app puts the ids of every front on an SQS queue. These are pulled in bunches (of up to 10) every 10 seconds by Presser instances, and `pressed.json` file
> batches?
> regenerated?

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/facia/facia-monitoring.md
> +* __Detail__ : due to momentary ContentApi unavailability or increased latency somewhere in the network - pressing will on occasion fail. Above a certain frequency, these failures should be considere
> an

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/facia/facia-monitoring.md
> +* __Detail__ : due to momentary ContentApi unavailability or increased latency somewhere in the network - pressing will on occasion fail. Above a certain frequency, these failures should be considere
> an

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/facia/facia-monitoring.md
> +* __Consequence__ : if the metric exceeds 10 seconds, an "orange" alert appears in the tool UI with an option to "try again". The condition occurs on occasion due to momentary high latency somewhere
> recur

2017-04-28 11:36 UTC, kelvin-chappell commented on docs/02-architecture/02-fronts-architecture.md
> +The cron job is very important since content for a front can be coming from CAPI and change without any update from the Fronts tool.
Perhaps mention the different pressing priorities of editorial, commercial and training pages?

2017-04-28 12:58 UTC, TBonnin commented on docs/02-architecture/02-fronts-architecture.md
> -The global list of defined fronts - and the definitions of the collections on those fronts - is held in a single configuration file (`config.json`). This file is edited using the Configuration Tool.
This is mentioned here https://github.com/guardian/frontend/pull/16585/files#diff-19b63a5be14591333d80dbbb4586251aR21

2017-04-28 12:59 UTC, TBonnin commented on docs/02-architecture/02-fronts-architecture.md
> +The cron job is very important since content for a front can be coming from CAPI and change without any update from the Fronts tool.
Good idea. will do

2017-04-28 13:00 UTC, TBonnin commented on docs/02-architecture/02-fronts-architecture.md
> +1. Get the collections that compose the front by fetching the Fronts config at `s3://facia-tool-store/STAGE/frontsapi/config/config.json` in the CMS Fronts account. This file is edited using the Conf
No it is host on the same domain. Just adding `/config` to the Fronts tool url leads you to the Configs

2017-04-28 14:04 UTC, TBonnin commented on docs/02-architecture/02-fronts-architecture.md
> +```
👍  https://github.com/guardian/frontend/pull/16585/commits/3c89223ac1ed246dc4d7f53f64ec667d5a2b09e3

2017-04-28 14:04 UTC, TBonnin commented
@kelvin-chappell Thank you for the review. I think I have addressed most of your feedback

2017-04-28 14:05 UTC, TBonnin commented on docs/02-architecture/02-fronts-architecture.md
> +The cron job is very important since content for a front can be coming from CAPI and change without any update from the Fronts tool.
Done https://github.com/guardian/frontend/pull/16585/commits/90eba948e7b14172f5c0b2c53e266fa470a86f2d

2017-04-28 15:04 UTC, kelvin-chappell commented
👍

2017-04-28 16:35 UTC, merged