add always ask if tagged test
guardian/frontend pull request #16901
Opened 2017-05-25 15:12 UTC by jranks123

## What does this change?

This PR adds a "test" to the framework (inverted commas cause, like the ask 4 earning "test", it is an earner rather than a learner). 

It's primary function is to allow us to turn the epic always on for a single or multiple tags, as selected in the targetting tool (https://targeting.gutools.co.uk/#).

It ignores the sensitive flag, so any articles tagged with and whitelisted tags will show the epic, regardless of whether they are sensitive or not. This is the desired behaviour, as it solves a probelm we have sometimes where an article is marked as sensitive for reasons that shouldn't stop us showing our asks on them.

It also allows us to go into Hyper Modez™ when big events happen and we want to guarantee that certain stories display the epic. 

It will always display the control version of the epic. 

## What is the value of this and can you measure success?

## Does this affect other platforms - Amp, Apps, etc?

## Screenshots
This is what the control epic looks like currently:
<img width="667" alt="control" src="https://cloud.githubusercontent.com/assets/2844554/26456426/ece0cf4c-4164-11e7-8f16-033e976a7fc1.png">

## Tested in CODE?

2017-05-25 15:30 UTC, joelochlann requested changes
If you're expecting this to work for interactives, I think you'll need to change this bit:

https://github.com/guardian/frontend/blob/master/static/src/javascripts-legacy/projects/common/modules/commercial/contributions-utilities.js#L100

2017-05-25 16:13 UTC, dominickendrick commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/acquisitions-epic-pre-election.js
> +
remove ?

2017-05-25 16:13 UTC, dominickendrick commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/acquisitions-epic-always-ask-if-tagged.js
> +        expiry: '2018-07-19',
Should we set this to be a longer test if its going to be used generically ?

2017-05-25 16:14 UTC, dominickendrick approved these changes

2017-05-26 12:42 UTC, closed without merging

2017-05-26 12:42 UTC, jranks123 commented
closed and replaced with this PR : https://github.com/guardian/frontend/pull/16913