Epic for the Brexit cohort
guardian/frontend pull request #17204
Opened 2017-06-20 16:03 UTC by lmath

## What does this change?
Users who 

- Are logged in
- Joined as members after 23-06-2016 and before 31-07-3016, and have this date stored in the table
- Are on a page with tag 'politics/eu-referendum'

Will see a special epic message with a limit of 4 impressions in any given 30 days

If any of those three conditions are not met, the epic should not be shown. 

Note:

- [PR 192 in members-data-api](https://github.com/guardian/members-data-api/pull/192) exposes membershipJoinDate on calls to /me/features endpoint if it's available in the table. It's still necessary to backfill this data for existing members in the table. 
- If why the [build on my branch](https://teamcity.gu-web.net/viewLog.html?buildId=38287&buildTypeId=dotcom_frontend&tab=buildLog) is failing looks familiar to anyone please give me a hint! 🙏 

## What is the value of this and can you measure success?
We get to show a special message to our Brexit cohort and use make use of some that lovely existing code to create epics. 

## Does this affect other platforms - Amp, Apps, etc?

## Screenshots
logged in member in brexit cohort
![image](https://user-images.githubusercontent.com/3072877/27340718-1bb866e0-55d3-11e7-951e-6d2494ee3495.png)
![image](https://user-images.githubusercontent.com/3072877/27340758-395a2f12-55d3-11e7-89e3-5187507b74cc.png)

## Tested in CODE?

2017-06-20 17:27 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png)



**Exceptions** (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/thrown-exceptions.js)





**A11y validation** (0)
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/a11y-report.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17204/loadtesting.txt)


    
--automated message

2017-06-21 08:25 UTC, dominickendrick commented
@guardian/contributions

2017-06-21 08:25 UTC, dominickendrick approved these changes

2017-06-21 10:20 UTC, gustavpursche commented on static/src/javascripts/projects/commercial/modules/user-features.js
> +const toDate = (dateStr: string) => {
Would it be possible to type the return value?

2017-06-21 12:52 UTC, desbo commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/epic-for-brexit-cohort.js
> +    function worksWellWithPageTemplate() {
this is included as part of the standard `canRun` check in contributions utilities. If you remove `overrideCanRun` and still provide a `canRun` function that includes your brexit tag check, you'll get the page template check (and some other stuff) for free

2017-06-21 12:52 UTC, desbo commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/epic-for-brexit-cohort.js
> +    function hasBrexitTag(){
you might want to use the targeting tool instead of hardcoding this - give me a shout if you want to know how

2017-06-21 12:53 UTC, desbo commented on static/src/javascripts/projects/common/modules/experiments/ab-tests.js
> +    new EpicForBrexitCohort(),
this test should be added to `acquisitions-test-selector` rather than here, otherwise there's a danger of two epics showing up together

2017-06-21 12:54 UTC, desbo commented on static/src/javascripts/projects/common/modules/experiments/ab-tests.js
> +    new EpicForBrexitCohort(),
ah, I see you've added it to the selector, so you can just remove it from here

2017-06-21 13:11 UTC, desbo requested changes
please at least remove the entry from `ab-tests` before releasing

2017-06-21 13:57 UTC, lmath commented on static/src/javascripts/projects/common/modules/experiments/ab-tests.js
> +    new EpicForBrexitCohort(),
Oh good point! I've done this.

2017-06-21 15:37 UTC, lmath commented on static/src/javascripts-legacy/projects/common/modules/experiments/tests/epic-for-brexit-cohort.js
> +    function hasBrexitTag(){
Thanks for showing me the targeting tool. I will keep it in mind next time.

2017-06-21 15:38 UTC, desbo approved these changes
nice 👍

2017-06-22 09:03 UTC, merged