update discussion switch to stop all requests from frontend
guardian/frontend pull request #17622
Opened 2017-08-10 13:35 UTC by Calum-Campbell

## What does this change?
- Create new discussion-frontend switch that will completely kill requests to DAPI from Frontend (and consume the behaviour of the old UI switch into this one).
- Will also remove the comment and discussion UI from the site

## What is the value of this and can you measure success?
- Creates a single switch for the frontend to turn of commenting, discussion and requests to DAPI.
- This is clearer than the old switch which just turned off UI on web. 

## Does this affect other platforms - Amp, Apps, etc?
Shouldn't do

## Screenshots
 
![image](https://user-images.githubusercontent.com/14179210/29172814-12e12632-7dd9-11e7-9f50-550c91d2cdf9.png)

## Tested in CODE?
Not yet

2017-08-10 14:33 UTC, TBonnin commented on common/app/conf/switches/DiscussionSwitches.scala
> +  val DiscussionStopTrafficFromDotcom = Switch(
From a frontend perspective I prefer to see this switch as "disabling discussion". Why not naming it `DisableDiscussionSwitch` with a description that mention it removes the discussion UI as well as blocking all traffic from frontend to DAPI?

2017-08-10 14:51 UTC, TBonnin requested changes
I added some feedback about the switch name.
Also isn't the client side making any call to DAP directly?

2017-08-10 14:51 UTC, TBonnin commented on discussion/app/discussion/api/DiscussionApi.scala
> +      throw ServiceUnavailableException("Request from Dotcom to Discussion are currently unavailable")
The return type of this method is a `Future` I think. It would be better to return a Future.failed(...) rather than throwing an exception

2017-08-10 14:51 UTC, TBonnin commented on discussion/app/discussion/api/DiscussionApi.scala
> +      throw ServiceUnavailableException("Request from Dotcom to Discussion are currently unavailable")
Same comment about returning a `Future`

2017-08-10 14:51 UTC, TBonnin commented on discussion/app/discussion/api/DiscussionApi.scala
> +      throw ServiceUnavailableException("Request from Dotcom to Discussion are currently unavailable")
It is also be possible to handle duplication by creating something like that:
```
private def failIfDisabled: Future[Unit] = if(switchIsOn) Future.failed(...) else Future.successful(())
```

and then do:
```
failIfDisabled.flatMap(_ => super.getJsonOrError(url, onError, headers :+ guClientHeader: _*))
...
```

What do you think?

2017-08-11 08:50 UTC, Calum-Campbell commented on common/app/conf/switches/DiscussionSwitches.scala
> +  val DiscussionStopTrafficFromDotcom = Switch(
Yeah I agree actually. It will stop the double negatives in the javascript as well.

2017-08-11 09:41 UTC, Calum-Campbell commented on discussion/app/discussion/api/DiscussionApi.scala
> +      throw ServiceUnavailableException("Request from Dotcom to Discussion are currently unavailable")
Yep looks good to me. Updated

2017-08-11 09:46 UTC, Calum-Campbell commented
@TBonnin Agree with the name change and other comments. 
Regarding the client side, it is making calls but this will remove the client-side UI and then the client side just hits DAPI directly so a switch to disable DAPI is in the dynamo switchboard and hopefully soon a discussion frontend UI.

2017-08-11 15:09 UTC, TBonnin commented on discussion/app/discussion/api/DiscussionApi.scala
> +  private def failIfDisabled: Future[Unit] = if(EnableDiscussionSwitch.isSwitchedOn) Future.successful(()) else Future.failed(ServiceUnavailableException("DAPI is currently unavailable from Frontend"
This line is a bit long, no?

2017-08-11 15:10 UTC, TBonnin commented
>the client side just hits DAPI directly

Is the code responsible for it behind the switch?

2017-08-11 16:48 UTC, Calum-Campbell commented on static/src/javascripts-legacy/projects/common/modules/discussion/api.js
> +        if (config.switches.enableDiscussionSwitch) {
@nicl  This is just future proofing the JS incase a feature is added that might execute this code and doesn't live in the discussionFooter html, what do you think?

2017-08-11 17:00 UTC, TBonnin commented on static/src/javascripts-legacy/projects/common/modules/discussion/api.js
> +            throw new Error('Discussion API is currently disabled for frontend');
is it a reader visible error? If what about making it less technical like `Discussion features have been disabled`

2017-08-14 09:07 UTC, Calum-Campbell commented on static/src/javascripts-legacy/projects/common/modules/discussion/api.js
> +            throw new Error('Discussion API is currently disabled for frontend');
Yep happy with that.

2017-08-14 09:20 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png)



**Exceptions** (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/thrown-exceptions.js)





**A11y validation** (0)
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/a11y-report.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17622/loadtesting.txt)


    
--automated message

2017-08-14 09:29 UTC, TBonnin approved these changes
Thank you @Calum-Campbell

2017-08-14 09:49 UTC, nicl approved these changes
👍 big improvement on current behaviour.

2017-08-14 09:49 UTC, nicl commented on common/app/conf/switches/DiscussionSwitches.scala
> +    "When OFF, no requests will be possible from dotcom to DAPI and the comment UI will be removed",
Does this include comment counts?

2017-08-14 09:49 UTC, nicl commented on static/src/javascripts-legacy/projects/common/modules/discussion/api.js
> +        if (config.switches.enableDiscussionSwitch) {
👍

2017-08-14 09:49 UTC, nicl commented on static/src/javascripts-legacy/projects/common/modules/discussion/api.js
> +            throw new Error('Discussion features have been disabled');
perhaps 'Discussion features' -> 'Discussion *calls*' ?

2017-08-14 10:10 UTC, Calum-Campbell commented on common/app/conf/switches/DiscussionSwitches.scala
> +    "When OFF, no requests will be possible from dotcom to DAPI and the comment UI will be removed",
Yep commentCounts calls jsonOrError where this check is.

2017-08-14 10:40 UTC, merged