Add support frontend master switch and use in Epic
guardian/frontend pull request #17986
Opened 2017-10-10 10:20 UTC by JustinPinner

## What does this change?
Adds a new master switch to control whether supporter traffic is sent to support.thegu...  or not, and used it in the epic's default button template.

## What is the value of this and can you measure success?
We're getting set up to switch over to the new support domain. This is the first step to being able to do that.

## Does this affect other platforms - Amp, Apps, etc?
No, web only

## Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?
N/A

## Screenshots
To follow.

## Tested in CODE?
Not yet, only locally.

2017-10-10 10:24 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png)



**Exceptions** (0)
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/thrown-exceptions.js)





**A11y validation** (4)
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/a11y-report.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-17986/loadtesting.txt)


    
--automated message

2017-10-10 10:41 UTC, gustavpursche commented on static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js
> +    config.switches.ukSupporterTrafficToNewSupportFrontend &&
config.get('switches.ukSupporterTrafficToNewSupportFrontend')

2017-10-10 12:11 UTC, svillafe commented on common/app/conf/switches/FeatureSwitches.scala
> +  val SupportFrontendActive = Switch(
Would we like to do this as a Test? I thought that would be permanent.

2017-10-10 16:28 UTC, Ap0c reviewed
Gave it a run locally, seems to work fine, nice! 🦋

2017-10-10 16:30 UTC, Ap0c commented
cc: @guardian/contributions

2017-10-11 10:05 UTC, joelochlann requested changes

2017-10-11 10:05 UTC, joelochlann commented on static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js
> +const contributionsBaseURL = useSupportDomain
You'll need to make changes to the liveblog copy too:

https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/experiments/tests/acquisitions-epic-liveblog.js#L166

https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/commercial/acquisitions-copy.js#L44

2017-10-11 10:21 UTC, joelochlann commented on static/src/javascripts/projects/common/modules/commercial/templates/acquisitions-epic-buttons.js
> +    const supportButton = `<div>
just being pedantic but I generally find these inline html blocks more readable with the opening tag on the next line

2017-10-11 14:30 UTC, JustinPinner commented
Hey @joelochlann are you ok with this now? Ta.

2017-10-11 15:01 UTC, joelochlann approved these changes
Looks good!

2017-10-11 15:04 UTC, merged

2017-10-12 11:21 UTC, joelochlann commented
Hi @JustinPinner, just wondering if the button CTA for the support site has been officially changed? It used to be "Support the Guardian" but here it's "Become a Supporter" - was that an editorial decision?

2017-10-12 12:43 UTC, JustinPinner commented
Hey @joelochlann, that's a good question. I think the Become a supporter button is one of the only things I didn't change in this PR. I'll ask around though, in case we need to change it.