(Behind switch) Redirect users with V1 consents to /consent
guardian/frontend pull request #18403
Opened 2017-12-04 18:05 UTC by walaura

## What does this change?
When its switch is enabled, redirects users going to `/email-preferences` (or any profile page at the moment) to `/consent?journey=repermission`so they can get their consents inline with the V2 ones. it also defines a second redirection to `/consent?journey=repermission-narrow` which will be used when a user has already repermissioned but created a new V1 email consent after that

## What is the value of this and can you measure success?
At the moment it is quite bad. The redirect checks for a verified account as there's no`hasRepermissioned` flag yet and work on splitting v1/v2 email consents is underway so that's not checked. I mostly wanted to get this ball rolling.

2017-12-04 18:11 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png)



&#x1F49A; **Exceptions**
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/thrown-exceptions.js)





&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/a11y-report.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/loadtesting.txt)



&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-18403/microdata.txt)

    
--automated message

2017-12-04 18:21 UTC, Calum-Campbell commented on identity/app/actions/AuthenticatedActions.scala
> +        request.user.statusFields.userEmailValidated match {
I would leave this until we actually set a hasRepermissioned flag to the User model?

2017-12-05 10:05 UTC, mariogalic approved these changes

2017-12-06 17:24 UTC, walaura commented on identity/app/actions/AuthenticatedActions.scala
> +    SeeOther(identityUrlBuilder.buildUrl(redirectUrlWithParams))
😤

2017-12-06 17:41 UTC, mariogalic requested changes
Remove ; !!

2017-12-06 17:43 UTC, mariogalic approved these changes

2017-12-06 18:30 UTC, walaura reviewed
extremely nice refactor! `sendUserToConsentJourney()` got lost in the way though, can you re-add it? :(

2017-12-07 11:15 UTC, mario-galic commented on identity/app/actions/AuthenticatedActions.scala
> +    val redirectUrlWithParams = identityUrlBuilder.appendQueryParams(path, List(
Yes this is correct usage: see [example](https://github.com/guardian/frontend/blob/23966052b872108014bd441dc651ab6e9d91365f/identity/test/services/IdentityUrlBuilderTest.scala#L67)

2017-12-07 11:23 UTC, merged