Remove PressedCollection updatedBy and updatedEmail
guardian/frontend pull request #18545
Opened 2017-12-19 14:25 UTC by nicl

These fields introduce unused PI data; let's remove them.

Should have no impact on users.

2017-12-19 16:34 UTC, TBonnin requested changes
Does that require repressing?

2017-12-19 16:34 UTC, TBonnin commented on common/app/model/facia/PressedCollection.scala
> +//  updatedEmail: Option[String],
remove them all together rather than commenting them

2017-12-19 18:19 UTC, nicl commented on common/app/model/facia/PressedCollection.scala
> +//  updatedEmail: Option[String],
ah thanks.

2017-12-19 18:22 UTC, nicl commented
@TBonnin re requiring re-pressing, I'd assumed not as the fields are optional, but I haven't tested on CODE yet.

2017-12-20 11:23 UTC, TBonnin approved these changes

2017-12-20 11:24 UTC, merged