Shows tags for analysis pieces
guardian/frontend pull request #19048
Opened 2018-02-01 15:30 UTC by Joshua-David

## What does this change?
Makes tags for analysis pieces visible, were hidden for some odd reason

Before:
<img width="897" alt="screen shot 2018-02-01 at 15 29 44" src="https://user-images.githubusercontent.com/8453924/35686723-db608c64-0764-11e8-9b19-fef5591f9db6.png">

After:
<img width="891" alt="screen shot 2018-02-01 at 15 29 34" src="https://user-images.githubusercontent.com/8453924/35686731-e042bc5c-0764-11e8-893f-1467cfa31688.png">

2018-02-01 15:37 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png) • [wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png)



&#x1F49A; **Exceptions**
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/thrown-exceptions.js)





&#x1F525; (failed)  **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/a11y-report.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/loadtesting.txt)



&#x1F525; (invalid)  **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-19048/microdata.txt)

    
--automated message

2018-02-01 18:21 UTC, NataliaLKB approved these changes

2018-02-01 18:23 UTC, NataliaLKB requested changes
This should be deleted instead of adding more code: https://github.com/guardian/frontend/blob/ca04ec214e926dba3d2645563a87237eee3c0904/static/src/stylesheets/module/content-garnett/_types.scss#L1399

2018-02-02 10:41 UTC, Joshua-David commented
@NataliaLKB whoops, removed all that

2018-02-02 10:51 UTC, NataliaLKB approved these changes

2018-02-02 15:32 UTC, merged