do not merge
guardian/frontend pull request #20133
Opened 2018-08-06 08:58 UTC by AWare

do not merge

2018-08-06 16:04 UTC, nicl commented
I really want to merge this PR.

2018-08-07 09:43 UTC, AWare commented
please don't

2018-08-07 12:24 UTC, philmcmahon requested changes
Please provide a more complete PR description :trollface:

2018-08-07 12:24 UTC, nicl approved these changes
Looks great LGTM.

Thanks for the hard work on this one @AWare .

2018-08-07 12:47 UTC, closed without merging