New font files
guardian/frontend pull request #20466
Opened 2018-10-04 13:40 UTC by GHaberis

## What does this change?

1. Replace all font assets in `frontend/static/src/fonts/` with new font files for:

- GuardianHeadline (noalts-not-hinted and noalt-autohinted)
- GuardianTextEgyptianWeb (noalts-not-hinted and noalt-autohinted)
- GuardianSansWeb (noalts-not-hinted and noalt-autohinted)

2. In `tools/__tasks__/compile/fonts/index.config.js` rename keys used for generating JSON endpoints and saving to `localStorage` to:

- `GuardianHeadline` ---> `GHGuardianHeadline`
- `GuardianTextEgyptianWeb` ---> `GuardianTextEgyptianWeb`
- `GuardianTextSansWeb` ---> `GuardianTextSans`

3. In `common/app/views/fragments/fontDefinitions.scala.html` rename keys used for hitting JSON endpoints and saving to `localStorage` to: 

- `GuardianHeadline` ---> `GHGuardianHeadline`
- `GuardianTextEgyptianWeb` ---> `GuardianTextEgyptianWeb`
- `GuardianTextSansWeb` ---> `GuardianTextSans`

*** Renaming keys used to store/retrieve the fonts from local storage will need to change to ensure user's with the old fonts in their local storage don't get stuck using these fonts.

4. In `tools/__tasks__/compile/fonts/index.config.js` update config so new font assets are encoded and the correct font-weights are used for the matching font files.

5. Updates `common/app/templates/inlineJS/blocking/loadFonts.scala.js` to remove logic for deciding whether to use `cleartype` hinting as the new fonts only have `auto` hinting variants.

6. Update font-family variables in `static/src/stylesheets/pasteup/typography/_src.scss` to:

- `Guardian Text Egyptian Web` ---> `Guardian Text Egyptian` ($f-serif-text)
- `Guardian Egyptian Web` ---> `Guardian Headline` ($f-serif-headline)
- `Guardian Text Sans Web` ---> `Guardian Text Sans` ($f-sans-serif-text)

## TODO

- Remove "kerning-off" logic, kerning-off variants for fonts have never been used and are no longer available, yet we have logic scattered throughout the code for supporting "kerning-off".

- Users browsing using a browser that doesn't support localStorage (Opera Mini) are served static `.css` assets with `font-face` definitions rather than the encoded fonts. The source for these `.css` files is at [webfonts-hinting-auto-kerning-on.scss](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/webfonts-hinting-auto-kerning-on.scss), [webfonts-hinting-cleartype-kerning-on.scss](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/webfonts-hinting-cleartype-kerning-on.scss) and [webfonts-hinting-off-kerning-on.scss](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/webfonts-hinting-off-kerning-on.scss). We should remove the `webfonts-hinting-cleartype-kerning-on.scss` file. The remaining 2 need to be updated to use the new `font-family` names, and [_src.scss](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/pasteup/fonts/_src.scss) also needs to be updated to point to the new font assets (where they're hosted TBC!). We can then update 
[javaScriptConfig.scala.js](https://github.com/guardian/frontend/blob/master/common/app/templates/javaScriptConfig.scala.js) to remove the `cleartype` option in `window.guardian.config.stylesheets.fonts` and also remove the unnecessary `kerningOn` nesting. **Until we do this users on without localStorage won't see our webFonts!**.
- Update the hardcoded font-loading logic in [error.scala.html](https://github.com/guardian/frontend/blob/master/identity/app/views/errors/error.scala.html) and [notFound.scala.html](https://github.com/guardian/frontend/blob/master/archive/app/views/notFound.scala.html) to use the new `window.guardian.config.stylesheets.fonts`fallbacks. **The localStorage fallback logic is already broken on these templates!**

## Screenshots

## What is the value of this and can you measure success?

The new files are more performant and they contain wider character sets. 

## Checklist

### Does this affect other platforms?

- AMP - This doesn't change the CSS or font files used on our AMP templates.
- Email Templates - This doesn't change the CSS or font files used on our AMP templates.

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

The following keys used by [commercial templates](https://github.com/guardian/commercial-templates/blob/master/src/_shared/js/messages.js#L69-L74
) will need updating and font-family names in the CSS will also need to updated.

### Does this change break ad-free?

No

2018-10-04 13:47 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)



&#x1F49A; **Exceptions**
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/thrown-exceptions.js)





&#x1F525; (failed)  **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/a11y-report.txt)



&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/microdata.txt)

    

**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/loadtesting.txt)



**LightHouse Reporting**
[lighthouse.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20466/lighthouse.html)


    
--automated message

2018-10-04 14:18 UTC, paperboyo reviewed
💎 This is great. Waited for years. (These two days feel like Christmas somehow 🤔)

1. Minor, in description pt. 1:
GuardianTextEgyptianWeb should read GuardianTextEgyptian
GuardianSansWeb should read GuardianTextSans (GuardianSansWeb was a headline version of Sans replaced by TextSans to save weight long time ago).

2. Is there a reason to keep old GuardianTextEgyptianWeb name in pt. 3 (get rid of Web if possible)?

3. In [here](https://github.com/guardian/frontend/blob/gh-new-font-files/tools/__tasks__/compile/fonts/index.config.js) you rightly used noalts subset in woff2 unhinted format. But you also have used noalts subsets for weightier file formats: woff, ttf and, especially, their autohinted versions. Before, these were, admittedly arbitrarily, restrained to sparser subsets for less important styles because of the weight. I strongly advice following this logic for everything but woff2 now too. We may be and should be more allowing than with old fonts (to have less ugly substitutions), because the new fonts are much leaner, but loading noalts everywhere is too optimistic. Otherwise the bundle size for these older OSes/browsers will balloon considerably (I have no numbers, but one old calc I made for TTF Autohinted was 753KB>1782KB!).

2018-10-04 15:06 UTC, GHaberis commented
@paperboyo thanks for your comment, points 1 and 2 were simply down to typo in the PR (I've updated the text in the original comment). Regarding point 3 that's great to know. 

> these were, admittedly arbitrarily, restrained to sparser subsets for less important styles because of the weight. I strongly advice following this logic for everything but woff2 now too. So:

- For `woff2` we should use the `noalts` subset across all weights? 
- For `woff` and `ttf` we should use the `latin1` subsets? Is this across all weights? Or should we use the `noalts` set for the 'regular' variant and `latin1` for the _italic_ and **bold** variants?

2018-10-04 17:19 UTC, katebee commented
@GHaberis CommDev work might take a while...

![shockcat](https://user-images.githubusercontent.com/8607683/46491198-f540fe80-c801-11e8-993f-a79dc9812f76.gif)

2018-10-04 22:04 UTC, paperboyo commented on tools/__tasks__/compile/fonts/index.config.js
>                  'font-weight': '300',
Regular weight should always be 400, I think. 300 is for Light. Also weight numbers are missing for Regular weights above for all flavours but ttf hinted.

2018-10-04 22:06 UTC, paperboyo commented on tools/__tasks__/compile/fonts/index.config.js
> +                src:
Font weight numbers similarly missing? (maybe this will fix TextSans Bold replacing Regular on CODE?)

2018-10-04 22:11 UTC, paperboyo commented on tools/__tasks__/compile/fonts/index.config.js
>                  src:
Regular weight should always be 400, I think. 300 is for Light. Also weight numbers are missing for Regular weights above for all flavours but ttf hinted.

2018-10-04 22:13 UTC, paperboyo commented on tools/__tasks__/compile/fonts/index.config.js
> +                'font-weight': '300',
Regular weight should always be 400, I think. 300 is for Light. Also weight numbers are missing for Regular weights above for all flavours but ttf hinted.

2018-10-04 22:20 UTC, paperboyo commented on tools/__tasks__/compile/fonts/index.config.js
>                  'font-weight': '300',
Regular weight should always be 400, I think. 300 is for Light. Also weight numbers are missing for Regular weights above for all flavours but ttf hinted.

2018-10-05 09:08 UTC, GHaberis commented
> I can’t even leave a comment so that it’s not outdated

I think I get the gist of the comments, ok...

So reagrding missing font-weights I followed the existing `index.config.js` as guidance. In that file  `font-weight` is not explicitly defined for `Regular` variants of `GuardianTextSansWeb` and `GuardianTextEgyptianWeb`. I'm happy to explicitly associate Regular with `'font-weight': '400'`.

Anywhere you've seen `'font-weight': '300'` mapping to `Regular` variants is a mistake which I'll correct (map to `'font-weight': '300'`) now!

2018-10-05 09:54 UTC, paperboyo commented
> In that file `font-weight` is not explicitly defined for `Regular` variants of `GuardianTextSansWeb` and `GuardianTextEgyptianWeb`. I'm happy to explicitly associate `Regular` variants with `'font-weight': '400'`.

I honestly don’t know if that’s needed. If any kind of resetting or a notion of “main weight” is necessary/useful for dotcom or other entities using these… E.g. I have no idea if these foundry-provided files (“fonts.css”) added in this PR are even used by anything. If it isn’t – superb!

> Anywhere you've seen `'font-weight': '300'` mapping to `Regular` variants is a mistake which I'll correct (map to `'font-weight': '400'`) now!

Thanks! Just this one place, I think.

2018-10-05 10:49 UTC, GHaberis commented
> I honestly don’t know if that’s needed. If any kind of resetting or a notion of “main weight” is necessary/useful for dotcom or other entities using these… 

I've tested and I don't believe it's needed. Without explicitly mapping `font-weight: 400` to `Regular` you get `Regular` on any `font-weight` < 600, after that with `font-weight` >= 600 you get `Bold`. After  explicitly mapping `font-weight: 400` to `Regular` I see exactly the same behaviour. 

> E.g. I have no idea if these foundry-provided files (“fonts.css”) added in this PR are even used by anything. If it isn’t – superb!

They're not!

2018-10-05 11:22 UTC, SiAdcock approved these changes
This looks 💎, nice one @GHaberis!

2018-10-05 11:39 UTC, paperboyo commented
Not sure if it belongs to this PR (whatever’s easiest), but we’ve just discovered that one style of GH Guardian Headline is only used in one-and-a-half places on the site and Design decided to remove it completely 🎆 :
GH Guardian Headline Semibold

I will make a case to fix some faux styles separately, but now the case is stronger 😉 .

And a little thing, I can see on CODE:
![image](https://user-images.githubusercontent.com/6032869/46533202-b069a600-c89b-11e8-8dab-b17531635c78.png)
Is there a reason the family name is missing `GH` at the beginning of it’s name?

2018-10-05 13:43 UTC, katebee requested changes
Not a change here so much as a request to hold while we roll out changes to the DFP templates 🙏 

Are the current fonts going to vanish completely once this is merged? If so we probably need to coordinate the DFP updates 🙈 ...or maybe another option is for CommDev to check for both fonts and use the one available... 🤔

2018-10-05 13:48 UTC, GHaberis commented
@paperboyo 

>  we’ve just discovered that one style of GH Guardian Headline is only used in one-and-a-half places on the site and Design decided to remove it completely

Does this mean I can remove `GHGuardianHeadline-Semibold` from `index.config.js`?

> Is there a reason the family name is missing `GH` at the beginning of it’s name?

No, I've just referred to the foundries `.css` and they've defined the family as "GH Guardian Headline" so for consistencies sake I'll update to do the same!

2018-10-05 13:52 UTC, GHaberis commented
> Are the current fonts going to vanish completely once this is merged? 

@katebee let's chat about this. The current fonts won't vanish from user's local storage after this PR is merged, if they have them they'll remain there so when DFP ads request them they'll be returned as they are now. The current fonts won't however be stored in localStorage for any new users. The only thing I'm unsure of is how the commercial templates behave if the fonts they request via postMessage aren't in local storage.

2018-10-05 16:00 UTC, GHaberis commented
Having looked into this it appears the renaming of the `localStorage` keys and the `font-family` names may cause commercial some disruption as they have hardcoded references to these keys/family names in code for each template uploaded to DFP. 

If we reuse the existing keys (`GuardianHeadline`/`GuardianTextEgyptianWeb`/`GuardianTextSansWeb`) and family-names (`Guardian Egyptian Web`/`Guardian Text Egyptian Web`/`Guardian Text Sans Web`) it should make the upgrade less disruptive for commercial, some font-weights on some templates may be off but that's it, they won't need to change the family-names in their css or the key references used for retrieving font styles.

I believe my original worry about needing to update the keys to invalidate the font styles already stored in local storage isn't a problem as the keys contain a hash which should update after this has been released (TBC by testing on CODE).

@katebee @paperboyo

2018-10-05 16:28 UTC, paperboyo commented
Whatever cause less disruption/work for friends in Commercial is good. Let’s just try to be (very, very slowly) prepared for calling them proper names once dotcomponents goodness arrives.

2018-10-08 09:45 UTC, GHaberis commented
@SiAdcock @paperboyo @katebee OK I've tested reusing the existing keys (`GuardianHeadline`/`GuardianTextEgyptianWeb`/`GuardianTextSansWeb`) and family-names (`Guardian Egyptian Web`/`Guardian Text Egyptian Web`/`Guardian Text Sans Web`) and it all works - so user's with the old font styles in their localStorage will have these removed and replaced with the new styles. And it won't require anywork from commercial!

2018-10-08 10:01 UTC, GHaberis commented
I've reverted the commit https://github.com/guardian/frontend/pull/20466/commits/32414a0db34884fef3643c50943c7faab1e4da74 where I deleted the old font files from the repo because of the 4000+ "files changed" by it meant you couldn't really view this PR in github! I'll remove these files in a separate PR.

2018-10-08 12:12 UTC, katebee approved these changes
> [commercial] won't need to change the family-names in their css or the key references used for retrieving font styles.

This is absolutely magic ✨Thank you for saving us a bunch of work!

👍 💎

2018-10-09 12:34 UTC, merged

2018-10-11 12:42 UTC, mchv commented
Excellent work @GHaberis 🎖