indent using 2 spaces in all files
guardian/frontend pull request #20631
Opened 2018-11-02 14:49 UTC by akash1810

## What does this change?
Indent using 2 spaces in all files. This is mainly because the twirl templates lean to the right sooooo much!

This will likely introduce some whitespace changes in new PRs as the templates are updated, but nothing too major.

## Screenshots
n/a

## What is the value of this and can you measure success?
Eyes move less.

## Checklist

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

2018-11-02 14:56 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)



&#x1F49A; **Exceptions**
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/thrown-exceptions.js)





&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/a11y-report.txt)



&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/microdata.txt)

    

**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/loadtesting.txt)



**LightHouse Reporting**
[lighthouse.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20631/lighthouse.html)


    
--automated message

2018-11-02 14:59 UTC, philmcmahon commented
Sounds good to me, 2 spaces makes sense when space is at a premium

2018-11-02 15:03 UTC, SiAdcock commented
Our prettier config insists JavaScript uses 4 spaces, so it would be better to exclude JavaScript files from this change

2018-11-02 15:17 UTC, nicl commented
@akash1810 can you expand on how this will interact with existing code? I am a bit concerned it will introduce inconsistent formatting going forward.

2018-11-02 15:22 UTC, akash1810 commented
@nicl `.editorconfig` provides hints to your IDE on, in this case, how many characters to use for indents.

> I am a bit concerned it will introduce inconsistent formatting going forward.

Agreed; the rule change will take effect only if a file gets changed in a PR. However, if the file isn't touched, then you wouldn't notice the inconsistency...

2018-11-02 15:38 UTC, NataliaLKB requested changes
the noise in future PRs and the risk that `git blame` would not be as useful anymore probably isn't worth this change. 

Stylistically, I don't really mind.

2018-11-05 13:14 UTC, akash1810 commented
I agree too!

I'll close this PR as:
- I'm not in this repo very often
- This hasn't been an issue to date
- Less whitespace is for vanity rather than functionality

2018-11-05 13:14 UTC, closed without merging

2018-11-05 14:35 UTC, NataliaLKB commented
Thanks @akash1810 !

2018-11-05 14:35 UTC, NataliaLKB commented
Thanks @akash1810 !