Remove in article audio switch
guardian/frontend pull request #20750
Opened 2018-11-22 10:32 UTC by regiskuckaertz

2018-11-22 10:39 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)



&#x1F49A; **Exceptions**
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/thrown-exceptions.js)





&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/a11y-report.txt)



&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/microdata.txt)

    

**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/loadtesting.txt)



**LightHouse Reporting**
[lighthouse.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-20750/lighthouse.html)


    
--automated message

2018-12-05 12:22 UTC, ajwl requested changes
Good. CSS also can get deleted:
https://github.com/guardian/frontend/blob/master/static/src/stylesheets/module/journalism/_inline-audio-player.scss
https://github.com/guardian/frontend/blob/master/static/src/stylesheets/head.content.garnett.scss#L55

2018-12-05 16:00 UTC, regiskuckaertz commented
Done

2018-12-05 17:09 UTC, ajwl approved these changes

2018-12-05 17:09 UTC, ajwl commented
👍

2018-12-06 10:35 UTC, merged