Merge WebPage and NewArticle structured data
guardian/frontend pull request #21249
Opened 2019-03-13 15:43 UTC by ademuk

## What does this change?
* Changes linked data from a list of `WebPage` and `NewsArticle`, to a single `NewsArticle`.
* Move `potentialAction` field from `Webpage` to `NewsArticle`.

## Screenshots
n/a

## What is the value of this and can you measure success?
* Having a `NewsArticle` and a `WebPage` arguably isn't necessary. I believe `DotcomponentsDataModel` currently only serves articles, so `NewsArticle` should be fine.
* As long as `NewsArticle.potentialAction` works the same as `WebPage.potentialAction`, i'm not sure about the exact purpose of `potentialAction`?
* Having structured data set as an array breaks our Subscribe with Google Amp extension (the real reason behind this PR 😜 ).

## Checklist

### Does this affect other platforms?

- [X] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [X] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [X] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [X] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [X] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [X] Locally
- [ ] On CODE (optional)

2019-03-13 16:25 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)



&#x1F525; (failed)  **Exceptions**
[thrown-exceptions.js](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/thrown-exceptions.js)





&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/a11y-report.txt)



&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/microdata.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/loadtesting.txt)



**LightHouse Reporting**
[1552494264.report.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21249/1552494264.report.html)



--automated message

2019-03-21 18:42 UTC, nicl requested changes
Hey, can we have a chat about this early next week? I think this is okay (I agree in theory there is no reason why webpage can't be subsumed into the newsarticle) but I've seen issues with this in the past and to be honest we don't have a good understanding of how Google uses this. More generally though, I think it's probably sensible to keep structured data as a list and manage your requirements in dotcom-rendering here.

2019-03-22 10:06 UTC, ademuk commented
Hi @nicl, apologises I've been meaning to follow up on this.

Yes, I've also been unable to get definitive info on `NewsArticle` vs `Webpage`. I need to read up more on `WebPage.potentialAction`.

Re. the structured data. `amp-subscription-google` doesn't play well with a list. Is a list valid schema do you know?

I'll do some further reading and then let's catch on Monday (or later today if you're around).

2019-03-26 11:08 UTC, ademuk commented
@nicl I cant find any reference on the web to `application/ld+json` being a list. I'm not convinced it's valid schema.

Therefore I think we have 2 options:

To keep both objects:
```
<script data-schema="Webpage" type="application/ld+json">
..potentialActionStuff
</script>
<script data-schema="NewsArticle" type="application/ld+json">
..restOfSchemaStuffRequiredBySwG
</script>
```

To switch to one object (as per this PR), we'd need to test that potentialAction worked with this:
```
<script type="application/ld+json">
{
  @type: "NewsArticle",
  ...potentialActionStuff,
  ...restOfSchemaStuffRequiredBySwG
}
</script>
```

2019-03-27 10:54 UTC, ademuk commented
Closing in favour of the multiple `script` tag approach.
https://github.com/guardian/dotcom-rendering/pull/475

2019-03-27 10:54 UTC, closed without merging