Mobile sticky support for DCR
guardian/frontend pull request #21911
Opened 2019-10-10 17:21 UTC by shtukas

## What does this change?

This enriches the `createAdWrapper` function in `mobile-sticky.js`, to support dotcom-rendering. In frontend classic the `mobilesticky-container` div is being created, but in DCR it will have been injected into the page server side (because we need to attach styles to it at that stage). 

Note that we have removed type information to deal with the fact that `document.querySelector` could return `null`.

2019-10-10 17:22 UTC, ioanna0 approved these changes

2019-10-10 17:29 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)







&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/a11y-report.txt)





&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/microdata.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/loadtesting.txt)



**LightHouse Reporting**
[1570728516.report.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-21911/1570728516.report.html)


--automated message

2019-10-11 10:23 UTC, ioanna0 requested changes
Need to rethink this PR please do not merge

2019-10-11 15:02 UTC, ioanna0 approved these changes

2019-10-11 15:03 UTC, shtukas commented
+1 from me

2019-10-11 15:03 UTC, merged