Move A9 to a 100% roll out
guardian/frontend pull request #22464
Opened 2020-04-02 13:05 UTC by GHaberis

## What does this change?

This PR rolls A9 out to 100% of the audience by removing the `amazonA9Test` A/B test it previously sat behind.

FYI an A9 feature switch already exists and is behind the `dfpEnv.hbImpl.a9` conditional check.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes

### Tested

- [x] Locally
- [x] On CODE (optional)

2020-04-02 13:06 UTC, GHaberis commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-a9.js
> -export const setupA9Once: () => Promise<void> = once(setupA9);
I checked and this `export` wasn't necessary so I've removed it.

2020-04-03 13:17 UTC, ripecosta requested changes
Can we put A9 init behind a switch? Seems like there's a a switch already created called `a9-header-bidding` but it's not being used.

2020-04-03 13:25 UTC, GHaberis commented
> Can we put A9 init behind a switch? Seems like there's a a switch already created called `a9-header-bidding` but it's not being used.

I mentioned above but the value of the A9 feature switch `a9-header-bidding` sits behind the `dfpEnv.hbImpl.a9` conditional check, so we're checking the switch already, just indirectly.

2020-04-03 13:42 UTC, ripecosta commented
> > Can we put A9 init behind a switch? Seems like there's a a switch already created called `a9-header-bidding` but it's not being used.
> 
> I mentioned above but the value of the A9 feature switch `a9-header-bidding` sits behind the `dfpEnv.hbImpl.a9` conditional check, so we're checking the switch already, just indirectly.

I see now. I searched the code base for the name of the switch and didn't find it but it seems we get its value differently.

2020-04-03 13:42 UTC, ripecosta approved these changes
👍 Good stuff

2020-07-17 09:38 UTC, GHaberis commented
@jeteve I'm just tidying up old branches of mine, is this PR still required or can I close it and delete the branch?

2020-08-28 10:20 UTC, mxdvl commented
Hi there!
Should this PR remain open? It's been around for a while and should probably either ship or be closed.
If it needs to remain open, could you please change the base branch to main? See mention above for context.

🧹💨 @GHaberis @ripecosta

2020-08-28 10:27 UTC, ioanna0 commented
This can be closed as is now obsolete. A9 has been released only to US

2020-08-28 10:27 UTC, closed without merging