Change email subscription text colour
guardian/frontend pull request #22858
Opened 2020-08-03 16:48 UTC by nitro-marky

## What does this change?

Changes the response text colour when signing up for daily email to white.

![subscription contrast](https://user-images.githubusercontent.com/35331926/89206486-457d7900-d5b1-11ea-81ec-b34c121530bc.png)

![Screenshot 2020-08-03 at 17 48 10](https://user-images.githubusercontent.com/35331926/89206672-85dcf700-d5b1-11ea-923a-023a804084bc.png)

2020-08-03 17:08 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)







&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/a11y-report.txt)





&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/microdata.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/loadtesting.txt)



**LightHouse Reporting**
[1596474448.report.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-22858/1596474448.report.html)


--automated message

2020-08-04 08:25 UTC, gtrufitt requested changes

2020-08-04 08:25 UTC, gtrufitt commented on static/src/stylesheets/module/email-signup/_form.scss
> +    color: #ffffff;
You're probably going to end up having the same problem in other places the email is used, so I would leave this as is and add the color override scoped to the Footer Mods section https://github.com/guardian/frontend/blob/ma/subscribe-text-fix/static/src/stylesheets/module/email-signup/_form.scss#L196

2020-09-02 15:05 UTC, mxdvl commented
Hi there!

Should this PR remain open? It's been around for a while and should probably either ship or be closed.
If it needs to remain open, could you please change the base branch to main? See mention above for context.

🧹💨 @nitro-marky

2020-11-16 11:59 UTC, closed without merging