ignore metals files
guardian/frontend pull request #23053
Opened 2020-09-30 10:15 UTC by sndrs

## What does this change?

ignores files created for use by the [vscode metals extension](https://scalameta.org/metals/docs/editors/vscode.html)

2020-09-30 10:23 UTC, shtukas approved these changes

2020-09-30 10:25 UTC, nicl approved these changes
Thanks!

2020-09-30 10:25 UTC, nicl requested changes
Actually we don't want to ignore all of project do we?

2020-09-30 10:28 UTC, PRBuilds commented
PRbuilds results:


**Screenshots**
[wide.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/wide.png) • [desktop.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/desktop.png) • [tablet.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/tablet.png) • [mobile.png](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/screenshots/books%252F2014%252Fmay%252F21%252Fguardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism/mobile.png)







&#x1F49A; **A11y validation**
[a11y-report.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/a11y-report.txt)





&#x1F49A; **Microdata Validation**
[microdata.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/microdata.txt)



**Apache Benchmark Load Testing**
[loadtesting.txt](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/loadtesting.txt)



**LightHouse Reporting**
[1601461677.report.html](https://s3-eu-west-1.amazonaws.com/prbuilds/PR-23053/1601461677.report.html)


--automated message

2020-09-30 10:35 UTC, sndrs commented
> Actually we don't want to ignore all of project do we?

sorry i didn't realise that wan't all metals stuff. have updated to only ignore the folders metals creates

2020-09-30 10:41 UTC, sihil commented
2p worth from an outsider looking in:
 - if bloop/metals are used by the whole team / are in scripts in the repo then they should be in the project `.gitignore`
 - if they are a choice that only some people use it's a user toolchain choice and should live in the users global gitignore.

2020-10-01 13:12 UTC, sndrs commented
til: https://docs.github.com/en/free-pro-team@latest/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

maybe question then is should everyone have to do this, or should a project make working on it as simple as possible?

2020-10-30 11:05 UTC, sndrs commented
closing this, not sure anyone wants it :)

2020-10-30 11:05 UTC, closed without merging