Remove type assertions from `prepare-googletag`
guardian/frontend pull request #24461
Opened 2021-12-01 16:25 UTC by mxdvl

## What does this change?

Small health PR to remove type assertions.

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots

## What is the value of this and can you measure success?

## Checklist

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

2021-12-01 17:14 UTC, arelra approved these changes

2021-12-01 17:14 UTC, arelra commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
> +	const targeting = getPageTargeting();
V.minor - can we inline `pubads` and `targeting`? I don't think we wouldn't lose much readability?

2021-12-02 11:42 UTC, arelra commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
>  const setPageTargeting = (): void => {
V minor again - I think we can do an implicit return now :)

2021-12-02 13:06 UTC, chrislomaxjones requested changes

2021-12-02 14:18 UTC, mxdvl commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
> +			: storage.session.set('gu.commercial.pageViews', 0);
I think it should either increment if it’s a valid number, or set it to 0 if it’s missing or invalid.

2021-12-02 14:42 UTC, chrislomaxjones commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
> +			: storage.session.set('gu.commercial.pageViews', 0);
The original logic reads to me "retrieve pageview count from localstorage or set to zero if you cant, then save that number plus one", so was there a case before where you'd set pageview as zero?

2021-12-02 14:43 UTC, chrislomaxjones commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
> +			: storage.session.set('gu.commercial.pageViews', 0);
Oh, unless of course you're not just replicating the logic from before!

2021-12-02 15:03 UTC, chrislomaxjones approved these changes
🏷️

2021-12-02 15:56 UTC, mxdvl commented on static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
> +			: storage.session.set('gu.commercial.pageViews', 0);
Actually, @chrislomaxjones, I’ve discovered that we’re not using this value anywhere, so removed in 7d0d98687cca1d2d4e179f852db74d6b7418e6b8. Thanks for taking a closer look!

2021-12-02 16:02 UTC, merged