Times of day abtest
guardian/frontend pull request #26736
Opened 2023-12-04 14:26 UTC by lindseydew

## What is the value of this and can you measure success?

## What does this change?
This adds an AB Test for testing varying the frequency of time of day when a user sees the sign in gate. 
https://github.com/guardian/dotcom-rendering/pull/9758

## Screenshots

## Checklist

- [ ] Tested locally, and on CODE if necessary
- [ ] Will not break dotcom-rendering
- [ ] Will not break our database – if updating CAPI, [updated and committed the database files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)
- [ ] Meets our accessibility [standards](https://github.com/guardian/recommendations/blob/e647ef695199ea3116ea20d827ef0f1364270a39/accessibility.md)
  - [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
  - [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#Keyboard)
  - [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#colour)

2023-12-05 11:46 UTC, vlbee approved these changes

2023-12-11 10:36 UTC, vlbee requested changes

2023-12-11 10:39 UTC, vlbee commented on static/src/javascripts/projects/common/modules/experiments/tests/sign-in-gate-times-of-day.js
> +    audience: 0.45,
If you release to code it's easy to check the test overlaps via the frontend admin tool AB test tab:
<img width="1434" alt="image" src="https://github.com/guardian/frontend/assets/32312712/100b68d9-62a7-4991-9bd2-54ec68186e3e">

2023-12-11 12:37 UTC, mxdvl approved these changes

2023-12-13 11:39 UTC, vlbee approved these changes

2023-12-13 11:39 UTC, merged

2023-12-14 10:14 UTC, mxdvl commented
@lindseydew this reintroduced an expired feature switch, `ab-deeply-read-article-footer` that was removed in #26752